<?php

return [
    'faq' => 'FAQ',
    'close' => 'Close',
    'intelligent_insights' => 'Intelligent Insights',
    'comparison_ai' => [
        'title' => 'Comparison AI',
        'modal' => [
            'title' => "Comparison A.I.",
            'body' => '<section>
                        <p>
                            Knowledge is gained from understanding and using Information (data/facts). All Knowledge
                            can be classified on the basis of its Information sources – Evidence (Pramana) based,
                            Estimation (Anumana) based, and Comparison (Upmana) based. Indian logic (Tarkashastra)
                            classifies Knowledge (Gyana) as – Pramana, Anumana, Upmana, and additionally, a
                            Non-Apparent (Apratyaksh) form of Knowledge known as Shabda-Gyan (Word Power).
                        </p>
                        <p>
                            Prarang’s <strong>Upmana</strong> is a tool to gain Knowledge by Comparison. Underlying
                            the tool is Prarang’s Analytics with Information classified (Evidence) and designed
                            (Estimated) from reliable World & Country data providers. Prarang does no surveys
                            itself.
                        </p>
                        <p>
                            Upmana offers new insights through four dependent layers of Comparisons:
                        </p>

                        <ul style="list-style: none;">
                            <li>
                                <h5>a. Comparison between Geographies</h5>
                                <p>
                                    Countries, States, Districts and Cities can be compared. It can even be used to
                                    do unconventional (“Apples and Oranges comparison” in English phrase!)
                                    geographic comparisons. For example – Cities/Districts vs Countries. A maximum
                                    of 5 Geographies can be simultaneously selected.
                                </p>
                            </li>

                            <li>
                                <h5>b. Comparison by Ranks</h5>
                                <p>
                                    A unique ranking system is the DNA of Prarang’s Analytics. All conventional
                                    Metrics of 195 Countries are ranked from top to bottom, as well as ranked for
                                    deviation from Average (Samana). Similarly, all conventional metrics of
                                    approximately 800 cities/districts of India are also ranked in this manner.
                                </p>
                            </li>

                            <li>
                                <h5>c. Comparison of Metrics (Anything Measurable)</h5>
                                <p>
                                    Unconventional comparisons create new insights. Upmana allows you to actually
                                    compare Apple production in one country with Orange production in another and/or
                                    Gold production in a third! A maximum of 5 different Metrics can be
                                    simultaneously selected.
                                </p>
                            </li>

                            <li>
                                <h5>d. Comparison with GenAI Prompts</h5>
                                <p>
                                    The Comparison output generated by Prarang’s Upmana can also be compared (on the
                                    same Prompt instruction) with GenAI (Generative Artificial Intelligence) outputs from
                                    Meta’s Llama, Google’s Gemini, Microsoft’s ChatGPT, and others, on a single
                                    click.
                                </p>
                            </li>
                        </ul>

                        <p>
                            Your research using Upmana’s Comparison outputs can be easily saved and/or shared with
                            others.
                        </p>
                    </section>'
        ]

    ],
    'prompt' => [
        'title' => 'Prompt',
        'modal' => [
            'title' => 'Prompt',
            'body' => '
                  <section>
                        <p>
                            A prompt is a question, command, or statement used to interact between a human and an
                            GenAI (Generative Artificial Intelligence) model that allows the model to produce the
                            intended output. An GenAI model can provide several outputs based on how the prompt is
                            phrased. The purpose of the prompt is to provide the GenAI model with enough information
                            so that it can produce output relevant to the prompt.
                        </p>
                        <p>
                            Upmana assists you in generating a more precise and meaningful prompt for GenAIs by
                            helping select some geographies and some measurable aspect (from a vast array of world
                            and country metrics).
                        </p>
                    </section>',
        ]
    ],
    'com_ai_agi' => [
        'title' => 'Comparison A.I & Generative Artificial Intelligence (GenAI)',
        'modal' => [
            'title' => 'Comparison A.I & Generative Artificial Intelligence (GenAI)',
            'body' => ' <section>


                        <p>Information is not Knowledge. Knowledge is not Intelligence. Intelligence is not
                            Wisdom.</p>

                        <p>
                            <b>Information</b> is structured & organized data & facts, which are useful.
                            Understanding
                            information and related concepts creates <b>Knowledge</b>. Application of knowledge at
                            the
                            right time & place, is <b>Intelligence</b>. A broad understanding based on experience &
                            acquired knowledge, used for the betterment of self & society, is <b>Wisdom</b>.
                        </p>

                        <p>
                            Generative Artificial Intelligence (GenAI), using LLMs (Large Language Models), is a
                            method to reformat & restructure Information using a layer of new sentences/language
                            (based on word & word usage statistics on digitized content). It essentially seems to
                            skip the step of creating knowledge from Information. GenAI thus avoids "knowing".
                            Instead, based on the query/prompt, it tries to answer promptly, even mimicking human
                            “reasoning” to some extent.
                        </p>

                        <p>
                            Using brute computation power, GenAI is fast approaching a state of memorising all
                            known digitized Information & all known Languages of Mankind, with a man-designed
                            ability of connecting the two. This code/algorithms (man-designed) is where biases &
                            errors are coming in.
                        </p>

                        <p>
                            <strong>Prarang’s Upmana</strong> focuses on creating knowledge by comparison for its
                            users. It is not an GenAI yet, although it mimics the GenAI input prompt & its output is
                            comparable with GenAI outputs for the same prompt. Both GenAI & Upmana are still work in
                            progress. The difference is as follows:
                        </p>
                    </section>
                    <section>

                        <table style="width: 100%; border-collapse: collapse; text-align: left;">
                            <thead>
                                <tr style="background-color: #f2f2f2;">
                                    <th style="border: 1px solid #ddd; padding: 8px;"></th>
                                    <th style="border: 1px solid #ddd; padding: 8px;">GenAI <br><small>(Artificial
                                            General Intelligence)</small></th>
                                    <th style="border: 1px solid #ddd; padding: 8px;">Upmana <br><small>(Knowledge
                                            by Comparison)</small></th>
                                </tr>
                            </thead>
                            <tbody>
                                <tr>
                                    <td rowspan="3" style="border: 1px solid #ddd; padding: 8px;">Prompt Input</td>
                                    <td style="border: 1px solid #ddd; padding: 8px;">Can write &
                                        ask any question</td>
                                    <td style="border: 1px solid #ddd; padding: 8px;">Must select some Geographical
                                        & some Metric (any Measured) for Upmana to generate text</td>
                                </tr>
                                <tr>
                                <td style="border: 1px solid #ddd; padding: 8px;">Ability to do precise writing/summary.</td>
                                <td style="border: 1px solid #ddd; padding: 8px;">No ability to size/resize output</td>
                            </tr>
                                <tr>
                                    <td style="border: 1px solid #ddd; padding: 8px;" rowspan="3">Prompt Output
                                    </td>
                                    <td style="border: 1px solid #ddd; padding: 8px;">Text, data &
                                        images content, as instructed</td>
                                    <td style="border: 1px solid #ddd; padding: 8px;">Text & data content, as
                                        instructed</td>
                                </tr>
                                <tr>
                                <td style="border: 1px solid #ddd; padding: 8px;">Unstable Response : Unique sentences are created as answer for an identical prompt, on every attempt.</td>
                                <td style="border: 1px solid #ddd; padding: 8px;">Stable Response: Consistent output as answer for same prompt, on every attempt.</td>
                            </tr>
                                <tr>
                                    <td style="border: 1px solid #ddd; padding: 8px;">Hallucinations / errors
                                        sometimes in text & data</td>
                                    <td style="border: 1px solid #ddd; padding: 8px;">No hallucinations</td>
                                </tr>
                                <tr>
                                    <td style="border: 1px solid #ddd; padding: 8px;">Does not provide clear
                                        sources for its data</td>
                                    <td style="border: 1px solid #ddd; padding: 8px;">Always cites specific data
                                        source & year</td>
                                </tr>
                                <tr>
                                <td style="border: 1px solid #ddd; padding: 8px;">Ability to write software code.</td>
                                    <td style="border: 1px solid #ddd; padding: 8px;">Unable to write any software code</td>

                                </tr>
                                <tr>
                                    <td style="border: 1px solid #ddd; padding: 8px;" rowspan="6">Architecture
                                    </td>
                                    <td style="border: 1px solid #ddd; padding: 8px;">Generative AI
                                    </td>
                                    <td style="border: 1px solid #ddd; padding: 8px;">Traditional AI</td>
                                </tr>
                                <tr>
                                    <td style="border: 1px solid #ddd; padding: 8px;">Large Language Model (LLM)
                                    </td>
                                    <td style="border: 1px solid #ddd; padding: 8px;">Small Language Model
                                        (Language Localisation design)</td>
                                </tr>
                                <tr>
                                    <td style="border: 1px solid #ddd; padding: 8px;">Data sources –
                                        Screen-Scraping without citations</td>
                                    <td style="border: 1px solid #ddd; padding: 8px;">Large data Aggregation from
                                        reliable sources</td>
                                </tr>
                                <tr>
                                    <td style="border: 1px solid #ddd; padding: 8px;">LLM – Natural Language
                                        Processing (NLP) based on Western Linguistics</td>
                                    <td style="border: 1px solid #ddd; padding: 8px;">Analytics – Indian
                                        Linguistics (Tarkashastra) based</td>
                                </tr>
                                <tr>
                                    <td style="border: 1px solid #ddd; padding: 8px;">Word as Token – Extraordinary
                                        processing power for computation</td>
                                    <td style="border: 1px solid #ddd; padding: 8px;">Phoneme as Token – Under
                                        development, Unknown computation need</td>
                                </tr>
                                <tr>
                                    <td style="border: 1px solid #ddd; padding: 8px;">Photos – Recognition &
                                        Production: GANS (Generative Adversarial Network) and Diffusion Models</td>
                                    <td style="border: 1px solid #ddd; padding: 8px;">Photos – Under development
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </section>

',
        ]
    ],
    'world_ai_report' => 'World A.I. Report',
    'india_ai_report' => 'India A.I. Report',
    'world_development_planner' => 'World Development Planner',
    'world_market_planner' => 'World Market Planner',
    'india_development_planner' => 'India Development Planner',
    'india_market_planner' => 'India Market Planner',
    'india_city_sentiment_analytics' => 'India City Sentiment Analytics',
];
