<?php

return [
    'data' =>
    [
        [
            "id" => "1",
            "country" => "Algeria",
            "pop" => "47.4",
            "literacy" => "81%",
            "internate" => "70%",
            "facebook" => "26%",
            "internate_user" => "28%",
            "linkedin" => "12%",
            "twitter" => "1%",
            "cid" => "1"
        ],
        [
            "id" => "2",
            "country" => "Angola",
            "pop" => "39.0",
            "literacy" => "71%",
            "internate" => "38%",
            "facebook" => "2%",
            "internate_user" => "3%",
            "linkedin" => "4%",
            "twitter" => "0%",
            "cid" => "1"
        ],
        [
            "id" => "3",
            "country" => "Benin",
            "pop" => "14.8",
            "literacy" => "42%",
            "internate" => "33%",
            "facebook" => "2%",
            "internate_user" => "2%",
            "linkedin" => "5%",
            "twitter" => "0%",
            "cid" => "1"
        ],
        [
            "id" => "4",
            "country" => "Botswana",
            "pop" => "2.6",
            "literacy" => "89%",
            "internate" => "75%",
            "facebook" => "13%",
            "internate_user" => "10%",
            "linkedin" => "20%",
            "twitter" => "3%",
            "cid" => "1"
        ],
        [
            "id" => "5",
            "country" => "Burkina Faso",
            "pop" => "24.1",
            "literacy" => "39%",
            "internate" => "19%",
            "facebook" => "3%",
            "internate_user" => "1%",
            "linkedin" => "2%",
            "twitter" => "0%",
            "cid" => "1"
        ],
        [
            "id" => "6",
            "country" => "Burundi",
            "pop" => "14.4",
            "literacy" => "68%",
            "internate" => "11%",
            "facebook" => "1%",
            "internate_user" => "1%",
            "linkedin" => "1%",
            "twitter" => "0%",
            "cid" => "1"
        ],
        [
            "id" => "7",
            "country" => "Cameroon",
            "pop" => "29.9",
            "literacy" => "77%",
            "internate" => "42%",
            "facebook" => "3%",
            "internate_user" => "2%",
            "linkedin" => "5%",
            "twitter" => "0%",
            "cid" => "1"
        ],
        [
            "id" => "8",
            "country" => "Cape Verde",
            "pop" => "0.5",
            "literacy" => "87%",
            "internate" => "72%",
            "facebook" => "26%",
            "internate_user" => "26%",
            "linkedin" => "18%",
            "twitter" => "2%",
            "cid" => "1"
        ],
        [
            "id" => "9",
            "country" => "Central African Republic",
            "pop" => "5.5",
            "literacy" => "37%",
            "internate" => "10%",
            "facebook" => "0%",
            "internate_user" => "0%",
            "linkedin" => "1%",
            "twitter" => "0%",
            "cid" => "1"
        ],
        [
            "id" => "10",
            "country" => "Chad",
            "pop" => "21.0",
            "literacy" => "22%",
            "internate" => "12%",
            "facebook" => "1%",
            "internate_user" => "1%",
            "linkedin" => "1%",
            "twitter" => "0%",
            "cid" => "1"
        ],
        [
            "id" => "11",
            "country" => "Comoros",
            "pop" => "0.9",
            "literacy" => "59%",
            "internate" => "27%",
            "facebook" => "6%",
            "internate_user" => "3%",
            "linkedin" => "6%",
            "twitter" => "0%",
            "cid" => "1"
        ],
        [
            "id" => "12",
            "country" => "Democratic Republic of the Congo",
            "pop" => "112.8",
            "literacy" => "77%",
            "internate" => "26%",
            "facebook" => "1%",
            "internate_user" => "1%",
            "linkedin" => "1%",
            "twitter" => "0%",
            "cid" => "1"
        ],
        [
            "id" => "13",
            "country" => "Djibouti",
            "pop" => "1.2",
            "literacy" => "68%",
            "internate" => "64%",
            "facebook" => "2%",
            "internate_user" => "3%",
            "linkedin" => "8%",
            "twitter" => "1%",
            "cid" => "1"
        ],
        [
            "id" => "14",
            "country" => "Egypt",
            "pop" => "118.4",
            "literacy" => "71%",
            "internate" => "70%",
            "facebook" => "26%",
            "internate_user" => "17%",
            "linkedin" => "14%",
            "twitter" => "2%",
            "cid" => "1"
        ],
        [
            "id" => "15",
            "country" => "Equatorial Guinea",
            "pop" => "1.9",
            "literacy" => "95%",
            "internate" => "64%",
            "facebook" => "1%",
            "internate_user" => "3%",
            "linkedin" => "3%",
            "twitter" => "0%",
            "cid" => "1"
        ],
        [
            "id" => "16",
            "country" => "Eritrea",
            "pop" => "3.6",
            "literacy" => "77%",
            "internate" => "26%",
            "facebook" => "0%",
            "internate_user" => "1%",
            "linkedin" => "0%",
            "twitter" => "0%",
            "cid" => "1"
        ],
        [
            "id" => "17",
            "country" => "Ethiopia",
            "pop" => "135.5",
            "literacy" => "52%",
            "internate" => "19%",
            "facebook" => "1%",
            "internate_user" => "1%",
            "linkedin" => "1%",
            "twitter" => "0%",
            "cid" => "1"
        ],
        [
            "id" => "18",
            "country" => "Gabon",
            "pop" => "2.6",
            "literacy" => "85%",
            "internate" => "71%",
            "facebook" => "9%",
            "internate_user" => "6%",
            "linkedin" => "13%",
            "twitter" => "1%",
            "cid" => "1"
        ],
        [
            "id" => "19",
            "country" => "Gambia",
            "pop" => "2.8",
            "literacy" => "51%",
            "internate" => "52%",
            "facebook" => "5%",
            "internate_user" => "7%",
            "linkedin" => "6%",
            "twitter" => "1%",
            "cid" => "1"
        ],
        [
            "id" => "20",
            "country" => "Ghana",
            "pop" => "35.1",
            "literacy" => "79%",
            "internate" => "68%",
            "facebook" => "6%",
            "internate_user" => "7%",
            "linkedin" => "10%",
            "twitter" => "2%",
            "cid" => "1"
        ],
        [
            "id" => "21",
            "country" => "Guinea",
            "pop" => "15.1",
            "literacy" => "40%",
            "internate" => "33%",
            "facebook" => "6%",
            "internate_user" => "1%",
            "linkedin" => "3%",
            "twitter" => "0%",
            "cid" => "1"
        ],
        [
            "id" => "22",
            "country" => "Guinea Bissau",
            "pop" => "2.2",
            "literacy" => "60%",
            "internate" => "31%",
            "facebook" => "3%",
            "internate_user" => "2%",
            "linkedin" => "2%",
            "twitter" => "0%",
            "cid" => "1"
        ],
        [
            "id" => "23",
            "country" => "Ivory Coast",
            "pop" => "32.7",
            "literacy" => "90%",
            "internate" => "37%",
            "facebook" => "7%",
            "internate_user" => "3%",
            "linkedin" => "6%",
            "twitter" => "0%",
            "cid" => "1"
        ],
        [
            "id" => "24",
            "country" => "Kenya",
            "pop" => "57.5",
            "literacy" => "82%",
            "internate" => "40%",
            "facebook" => "5%",
            "internate_user" => "8%",
            "linkedin" => "12%",
            "twitter" => "2%",
            "cid" => "1"
        ],
        [
            "id" => "25",
            "country" => "Lesotho",
            "pop" => "2.4",
            "literacy" => "79%",
            "internate" => "46%",
            "facebook" => "3%",
            "internate_user" => "2%",
            "linkedin" => "6%",
            "twitter" => "1%",
            "cid" => "1"
        ],
        [
            "id" => "26",
            "country" => "Liberia",
            "pop" => "5.7",
            "literacy" => "48%",
            "internate" => "29%",
            "facebook" => "5%",
            "internate_user" => "2%",
            "linkedin" => "4%",
            "twitter" => "0%",
            "cid" => "1"
        ],
        [
            "id" => "27",
            "country" => "Libya",
            "pop" => "7.5",
            "literacy" => "91%",
            "internate" => "87%",
            "facebook" => "50%",
            "internate_user" => "30%",
            "linkedin" => "10%",
            "twitter" => "5%",
            "cid" => "1"
        ],
        [
            "id" => "28",
            "country" => "Madagascar",
            "pop" => "32.7",
            "literacy" => "77%",
            "internate" => "20%",
            "facebook" => "1%",
            "internate_user" => "1%",
            "linkedin" => "2%",
            "twitter" => "0%",
            "cid" => "1"
        ],
        [
            "id" => "29",
            "country" => "Malawi",
            "pop" => "22.2",
            "literacy" => "62%",
            "internate" => "17%",
            "facebook" => "1%",
            "internate_user" => "1%",
            "linkedin" => "2%",
            "twitter" => "0%",
            "cid" => "1"
        ],
        [
            "id" => "30",
            "country" => "Mali",
            "pop" => "25.2",
            "literacy" => "36%",
            "internate" => "32%",
            "facebook" => "2%",
            "internate_user" => "1%",
            "linkedin" => "2%",
            "twitter" => "0%",
            "cid" => "1"
        ],
        [
            "id" => "31",
            "country" => "Mauritania",
            "pop" => "5.3",
            "literacy" => "54%",
            "internate" => "43%",
            "facebook" => "8%",
            "internate_user" => "4%",
            "linkedin" => "4%",
            "twitter" => "1%",
            "cid" => "1"
        ],
        [
            "id" => "32",
            "country" => "Mauritius",
            "pop" => "1.3",
            "literacy" => "91%",
            "internate" => "76%",
            "facebook" => "51%",
            "internate_user" => "33%",
            "linkedin" => "51%",
            "twitter" => "11%",
            "cid" => "1"
        ],
        [
            "id" => "33",
            "country" => "Morocco",
            "pop" => "38.4",
            "literacy" => "74%",
            "internate" => "89%",
            "facebook" => "22%",
            "internate_user" => "38%",
            "linkedin" => "19%",
            "twitter" => "2%",
            "cid" => "1"
        ],
        [
            "id" => "34",
            "country" => "Mozambique",
            "pop" => "35.6",
            "literacy" => "61%",
            "internate" => "20%",
            "facebook" => "1%",
            "internate_user" => "2%",
            "linkedin" => "3%",
            "twitter" => "0%",
            "cid" => "1"
        ],
        [
            "id" => "35",
            "country" => "Namibia",
            "pop" => "3.1",
            "literacy" => "92%",
            "internate" => "60%",
            "facebook" => "9%",
            "internate_user" => "17%",
            "linkedin" => "17%",
            "twitter" => "1%",
            "cid" => "1"
        ],
        [
            "id" => "36",
            "country" => "Niger",
            "pop" => "27.9",
            "literacy" => "35%",
            "internate" => "16%",
            "facebook" => "1%",
            "internate_user" => "0%",
            "linkedin" => "1%",
            "twitter" => "0%",
            "cid" => "1"
        ],
        [
            "id" => "37",
            "country" => "Nigeria",
            "pop" => "237.5",
            "literacy" => "62%",
            "internate" => "34%",
            "facebook" => "4%",
            "internate_user" => "4%",
            "linkedin" => "5%",
            "twitter" => "2%",
            "cid" => "1"
        ],
        [
            "id" => "38",
            "country" => "Republic of Congo",
            "pop" => "6.5",
            "literacy" => "80%",
            "internate" => "35%",
            "facebook" => "2%",
            "internate_user" => "3%",
            "linkedin" => "5%",
            "twitter" => "0%",
            "cid" => "1"
        ],
        [
            "id" => "39",
            "country" => "Rwanda",
            "pop" => "14.6",
            "literacy" => "73%",
            "internate" => "33%",
            "facebook" => "1%",
            "internate_user" => "4%",
            "linkedin" => "4%",
            "twitter" => "1%",
            "cid" => "1"
        ],
        [
            "id" => "40",
            "country" => "Sao Tome and Principe",
            "pop" => "0.2",
            "literacy" => "93%",
            "internate" => "55%",
            "facebook" => "5%",
            "internate_user" => "5%",
            "linkedin" => "7%",
            "twitter" => "0%",
            "cid" => "1"
        ],
        [
            "id" => "41",
            "country" => "Senegal",
            "pop" => "18.9",
            "literacy" => "52%",
            "internate" => "58%",
            "facebook" => "5%",
            "internate_user" => "8%",
            "linkedin" => "8%",
            "twitter" => "1%",
            "cid" => "1"
        ],
        [
            "id" => "42",
            "country" => "Seychelles",
            "pop" => "0.1",
            "literacy" => "96%",
            "internate" => "84%",
            "facebook" => "36%",
            "internate_user" => "36%",
            "linkedin" => "48%",
            "twitter" => "4%",
            "cid" => "1"
        ],
        [
            "id" => "43",
            "country" => "Sierra Leone",
            "pop" => "8.8",
            "literacy" => "43%",
            "internate" => "29%",
            "facebook" => "3%",
            "internate_user" => "1%",
            "linkedin" => "2%",
            "twitter" => "0%",
            "cid" => "1"
        ],
        [
            "id" => "44",
            "country" => "Somalia",
            "pop" => "19.7",
            "literacy" => "39%",
            "internate" => "26%",
            "facebook" => "5%",
            "internate_user" => "2%",
            "linkedin" => "2%",
            "twitter" => "0%",
            "cid" => "1"
        ],
        [
            "id" => "45",
            "country" => "South Africa",
            "pop" => "64.7",
            "literacy" => "95%",
            "internate" => "73%",
            "facebook" => "15%",
            "internate_user" => "13%",
            "linkedin" => "26%",
            "twitter" => "3%",
            "cid" => "1"
        ],
        [
            "id" => "46",
            "country" => "South Sudan",
            "pop" => "12.2",
            "literacy" => "35%",
            "internate" => "12%",
            "facebook" => "1%",
            "internate_user" => "1%",
            "linkedin" => "1%",
            "twitter" => "0%",
            "cid" => "1"
        ],
        [
            "id" => "47",
            "country" => "Sudan",
            "pop" => "51.7",
            "literacy" => "61%",
            "internate" => "28%",
            "facebook" => "0%",
            "internate_user" => "0%",
            "linkedin" => "1%",
            "twitter" => "0%",
            "cid" => "1"
        ],
        [
            "id" => "48",
            "country" => "Swaziland",
            "pop" => "1.3",
            "literacy" => "88%",
            "internate" => "57%",
            "facebook" => "7%",
            "internate_user" => "6%",
            "linkedin" => "13%",
            "twitter" => "1%",
            "cid" => "1"
        ],
        [
            "id" => "49",
            "country" => "Tanzania",
            "pop" => "70.5",
            "literacy" => "78%",
            "internate" => "31%",
            "facebook" => "2%",
            "internate_user" => "7%",
            "linkedin" => "2%",
            "twitter" => "0%",
            "cid" => "1"
        ],
        [
            "id" => "50",
            "country" => "Togo",
            "pop" => "9.7",
            "literacy" => "67%",
            "internate" => "36%",
            "facebook" => "2%",
            "internate_user" => "2%",
            "linkedin" => "5%",
            "twitter" => "0%",
            "cid" => "1"
        ],
        [
            "id" => "51",
            "country" => "Tunisia",
            "pop" => "12.3",
            "literacy" => "82%",
            "internate" => "73%",
            "facebook" => "34%",
            "internate_user" => "31%",
            "linkedin" => "23%",
            "twitter" => "1%",
            "cid" => "1"
        ],
        [
            "id" => "52",
            "country" => "Uganda",
            "pop" => "51.4",
            "literacy" => "77%",
            "internate" => "10%",
            "facebook" => "1%",
            "internate_user" => "2%",
            "linkedin" => "4%",
            "twitter" => "1%",
            "cid" => "1"
        ],
        [
            "id" => "53",
            "country" => "Zambia",
            "pop" => "21.9",
            "literacy" => "87%",
            "internate" => "30%",
            "facebook" => "4%",
            "internate_user" => "3%",
            "linkedin" => "5%",
            "twitter" => "0%",
            "cid" => "1"
        ],
        [
            "id" => "54",
            "country" => "Zimbabwe",
            "pop" => "17.0",
            "literacy" => "87%",
            "internate" => "32%",
            "facebook" => "4%",
            "internate_user" => "4%",
            "linkedin" => "7%",
            "twitter" => "1%",
            "cid" => "1"
        ],
        [
            "id" => "55",
            "country" => "Afghanistan",
            "pop" => "43.8",
            "literacy" => "37%",
            "internate" => "18%",
            "facebook" => "3%",
            "internate_user" => "4%",
            "linkedin" => "2%",
            "twitter" => "0%",
            "cid" => "2"
        ],
        [
            "id" => "56",
            "country" => "Armenia",
            "pop" => "3.0",
            "literacy" => "100%",
            "internate" => "78%",
            "facebook" => "41%",
            "internate_user" => "49%",
            "linkedin" => "20%",
            "twitter" => "2%",
            "cid" => "2"
        ],
        [
            "id" => "57",
            "country" => "Azerbaijan",
            "pop" => "10.4",
            "literacy" => "100%",
            "internate" => "87%",
            "facebook" => "9%",
            "internate_user" => "41%",
            "linkedin" => "13%",
            "twitter" => "1%",
            "cid" => "2"
        ],
        [
            "id" => "58",
            "country" => "Bahrain",
            "pop" => "1.6",
            "literacy" => "98%",
            "internate" => "97%",
            "facebook" => "34%",
            "internate_user" => "73%",
            "linkedin" => "46%",
            "twitter" => "16%",
            "cid" => "2"
        ],
        [
            "id" => "59",
            "country" => "Bangladesh",
            "pop" => "175.7",
            "literacy" => "75%",
            "internate" => "44%",
            "facebook" => "18%",
            "internate_user" => "5%",
            "linkedin" => "7%",
            "twitter" => "0%",
            "cid" => "2"
        ],
        [
            "id" => "60",
            "country" => "Bhutan",
            "pop" => "0.8",
            "literacy" => "67%",
            "internate" => "86%",
            "facebook" => "39%",
            "internate_user" => "19%",
            "linkedin" => "18%",
            "twitter" => "1%",
            "cid" => "2"
        ],
        [
            "id" => "61",
            "country" => "China",
            "pop" => "1416.1",
            "literacy" => "97%",
            "internate" => "78%",
            "facebook" => "0%",
            "internate_user" => "0%",
            "linkedin" => "0%",
            "twitter" => "0%",
            "cid" => "2"
        ],
        [
            "id" => "62",
            "country" => "Georgia",
            "pop" => "3.8",
            "literacy" => "100%",
            "internate" => "82%",
            "facebook" => "67%",
            "internate_user" => "49%",
            "linkedin" => "24%",
            "twitter" => "4%",
            "cid" => "2"
        ],
        [
            "id" => "63",
            "country" => "India",
            "pop" => "1463.9",
            "literacy" => "74%",
            "internate" => "65%",
            "facebook" => "14%",
            "internate_user" => "32%",
            "linkedin" => "12%",
            "twitter" => "1%",
            "cid" => "2"
        ],
        [
            "id" => "64",
            "country" => "Iran",
            "pop" => "92.4",
            "literacy" => "86%",
            "internate" => "81%",
            "facebook" => "0%",
            "internate_user" => "0%",
            "linkedin" => "0%",
            "twitter" => "0%",
            "cid" => "2"
        ],
        [
            "id" => "65",
            "country" => "Iraq",
            "pop" => "47.0",
            "literacy" => "86%",
            "internate" => "76%",
            "facebook" => "29%",
            "internate_user" => "45%",
            "linkedin" => "6%",
            "twitter" => "4%",
            "cid" => "2"
        ],
        [
            "id" => "66",
            "country" => "Israel",
            "pop" => "9.5",
            "literacy" => "98%",
            "internate" => "90%",
            "facebook" => "43%",
            "internate_user" => "53%",
            "linkedin" => "34%",
            "twitter" => "6%",
            "cid" => "2"
        ],
        [
            "id" => "67",
            "country" => "Japan",
            "pop" => "123.1",
            "literacy" => "99%",
            "internate" => "86%",
            "facebook" => "8%",
            "internate_user" => "48%",
            "linkedin" => "5%",
            "twitter" => "46%",
            "cid" => "2"
        ],
        [
            "id" => "68",
            "country" => "Jordan",
            "pop" => "11.5",
            "literacy" => "98%",
            "internate" => "91%",
            "facebook" => "37%",
            "internate_user" => "39%",
            "linkedin" => "20%",
            "twitter" => "4%",
            "cid" => "2"
        ],
        [
            "id" => "69",
            "country" => "Kazakhstan",
            "pop" => "20.8",
            "literacy" => "100%",
            "internate" => "91%",
            "facebook" => "6%",
            "internate_user" => "60%",
            "linkedin" => "10%",
            "twitter" => "1%",
            "cid" => "2"
        ],
        [
            "id" => "70",
            "country" => "Kuwait",
            "pop" => "5.0",
            "literacy" => "97%",
            "internate" => "97%",
            "facebook" => "39%",
            "internate_user" => "62%",
            "linkedin" => "28%",
            "twitter" => "21%",
            "cid" => "2"
        ],
        [
            "id" => "71",
            "country" => "Kyrgyzstan",
            "pop" => "7.3",
            "literacy" => "100%",
            "internate" => "78%",
            "facebook" => "5%",
            "internate_user" => "53%",
            "linkedin" => "6%",
            "twitter" => "1%",
            "cid" => "2"
        ],
        [
            "id" => "72",
            "country" => "Lebanon",
            "pop" => "5.8",
            "literacy" => "95%",
            "internate" => "89%",
            "facebook" => "38%",
            "internate_user" => "50%",
            "linkedin" => "26%",
            "twitter" => "6%",
            "cid" => "2"
        ],
        [
            "id" => "73",
            "country" => "Maldives",
            "pop" => "0.5",
            "literacy" => "98%",
            "internate" => "83%",
            "facebook" => "57%",
            "internate_user" => "57%",
            "linkedin" => "40%",
            "twitter" => "14%",
            "cid" => "2"
        ],
        [
            "id" => "74",
            "country" => "Mongolia",
            "pop" => "3.5",
            "literacy" => "99%",
            "internate" => "82%",
            "facebook" => "58%",
            "internate_user" => "37%",
            "linkedin" => "10%",
            "twitter" => "2%",
            "cid" => "2"
        ],
        [
            "id" => "75",
            "country" => "Nepal",
            "pop" => "29.6",
            "literacy" => "68%",
            "internate" => "50%",
            "facebook" => "28%",
            "internate_user" => "15%",
            "linkedin" => "8%",
            "twitter" => "1%",
            "cid" => "2"
        ],
        [
            "id" => "76",
            "country" => "North Korea",
            "pop" => "26.6",
            "literacy" => "100%",
            "internate" => "0%",
            "facebook" => "0%",
            "internate_user" => "0%",
            "linkedin" => "0%",
            "twitter" => "0%",
            "cid" => "2"
        ],
        [
            "id" => "77",
            "country" => "Oman",
            "pop" => "5.5",
            "literacy" => "96%",
            "internate" => "90%",
            "facebook" => "22%",
            "internate_user" => "50%",
            "linkedin" => "24%",
            "twitter" => "12%",
            "cid" => "2"
        ],
        [
            "id" => "78",
            "country" => "Pakistan",
            "pop" => "255.2",
            "literacy" => "58%",
            "internate" => "32%",
            "facebook" => "10%",
            "internate_user" => "9%",
            "linkedin" => "7%",
            "twitter" => "1%",
            "cid" => "2"
        ],
        [
            "id" => "79",
            "country" => "Palestine",
            "pop" => "5.6",
            "literacy" => "97%",
            "internate" => "84%",
            "facebook" => "30%",
            "internate_user" => "33%",
            "linkedin" => "10%",
            "twitter" => "0%",
            "cid" => "2"
        ],
        [
            "id" => "80",
            "country" => "Qatar",
            "pop" => "3.1",
            "literacy" => "94%",
            "internate" => "97%",
            "facebook" => "63%",
            "internate_user" => "59%",
            "linkedin" => "61%",
            "twitter" => "14%",
            "cid" => "2"
        ],
        [
            "id" => "81",
            "country" => "Russia",
            "pop" => "144.0",
            "literacy" => "100%",
            "internate" => "93%",
            "facebook" => "0%",
            "internate_user" => "0%",
            "linkedin" => "0%",
            "twitter" => "0%",
            "cid" => "2"
        ],
        [
            "id" => "82",
            "country" => "Saudi Arabia",
            "pop" => "34.6",
            "literacy" => "98%",
            "internate" => "97%",
            "facebook" => "36%",
            "internate_user" => "55%",
            "linkedin" => "38%",
            "twitter" => "36%",
            "cid" => "2"
        ],
        [
            "id" => "83",
            "country" => "South Korea",
            "pop" => "51.7",
            "literacy" => "98%",
            "internate" => "98%",
            "facebook" => "8%",
            "internate_user" => "49%",
            "linkedin" => "10%",
            "twitter" => "14%",
            "cid" => "2"
        ],
        [
            "id" => "84",
            "country" => "Sri Lanka",
            "pop" => "23.2",
            "literacy" => "92%",
            "internate" => "50%",
            "facebook" => "19%",
            "internate_user" => "10%",
            "linkedin" => "13%",
            "twitter" => "1%",
            "cid" => "2"
        ],
        [
            "id" => "85",
            "country" => "Syria",
            "pop" => "25.6",
            "literacy" => "86%",
            "internate" => "34%",
            "facebook" => "19%",
            "internate_user" => "27%",
            "linkedin" => "0%",
            "twitter" => "0%",
            "cid" => "2"
        ],
        [
            "id" => "86",
            "country" => "Tajikistan",
            "pop" => "10.8",
            "literacy" => "100%",
            "internate" => "35%",
            "facebook" => "2%",
            "internate_user" => "20%",
            "linkedin" => "1%",
            "twitter" => "0%",
            "cid" => "2"
        ],
        [
            "id" => "87",
            "country" => "Turkey",
            "pop" => "87.7",
            "literacy" => "97%",
            "internate" => "81%",
            "facebook" => "26%",
            "internate_user" => "68%",
            "linkedin" => "25%",
            "twitter" => "16%",
            "cid" => "2"
        ],
        [
            "id" => "88",
            "country" => "Turkmenistan",
            "pop" => "7.6",
            "literacy" => "100%",
            "internate" => "21%",
            "facebook" => "0%",
            "internate_user" => "6%",
            "linkedin" => "1%",
            "twitter" => "0%",
            "cid" => "2"
        ],
        [
            "id" => "89",
            "country" => "United Arab Emirates",
            "pop" => "11.3",
            "literacy" => "98%",
            "internate" => "96%",
            "facebook" => "77%",
            "internate_user" => "78%",
            "linkedin" => "97%",
            "twitter" => "16%",
            "cid" => "2"
        ],
        [
            "id" => "90",
            "country" => "Uzbekistan",
            "pop" => "37.1",
            "literacy" => "100%",
            "internate" => "87%",
            "facebook" => "2%",
            "internate_user" => "39%",
            "linkedin" => "3%",
            "twitter" => "0%",
            "cid" => "2"
        ],
        [
            "id" => "91",
            "country" => "Yemen",
            "pop" => "41.8",
            "literacy" => "70%",
            "internate" => "17%",
            "facebook" => "2%",
            "internate_user" => "6%",
            "linkedin" => "2%",
            "twitter" => "2%",
            "cid" => "2"
        ],
        [
            "id" => "92",
            "country" => "Antigua and Barbuda",
            "pop" => "0.1",
            "literacy" => "99%",
            "internate" => "91%",
            "facebook" => "50%",
            "internate_user" => "49%",
            "linkedin" => "59%",
            "twitter" => "17%",
            "cid" => "3"
        ],
        [
            "id" => "93",
            "country" => "Barbados",
            "pop" => "0.3",
            "literacy" => "100%",
            "internate" => "76%",
            "facebook" => "41%",
            "internate_user" => "69%",
            "linkedin" => "67%",
            "twitter" => "22%",
            "cid" => "3"
        ],
        [
            "id" => "94",
            "country" => "Belize",
            "pop" => "0.4",
            "literacy" => "83%",
            "internate" => "69%",
            "facebook" => "41%",
            "internate_user" => "34%",
            "linkedin" => "28%",
            "twitter" => "4%",
            "cid" => "3"
        ],
        [
            "id" => "95",
            "country" => "Costa Rica",
            "pop" => "5.2",
            "literacy" => "98%",
            "internate" => "85%",
            "facebook" => "56%",
            "internate_user" => "52%",
            "linkedin" => "43%",
            "twitter" => "7%",
            "cid" => "3"
        ],
        [
            "id" => "96",
            "country" => "Cuba",
            "pop" => "10.9",
            "literacy" => "100%",
            "internate" => "74%",
            "facebook" => "0%",
            "internate_user" => "0%",
            "linkedin" => "0%",
            "twitter" => "0%",
            "cid" => "3"
        ],
        [
            "id" => "97",
            "country" => "Dominica",
            "pop" => "0.1",
            "literacy" => "92%",
            "internate" => "84%",
            "facebook" => "37%",
            "internate_user" => "37%",
            "linkedin" => "47%",
            "twitter" => "7%",
            "cid" => "3"
        ],
        [
            "id" => "98",
            "country" => "Dominican Republic",
            "pop" => "11.5",
            "literacy" => "94%",
            "internate" => "83%",
            "facebook" => "30%",
            "internate_user" => "43%",
            "linkedin" => "22%",
            "twitter" => "4%",
            "cid" => "3"
        ],
        [
            "id" => "99",
            "country" => "El Salvador",
            "pop" => "6.4",
            "literacy" => "89%",
            "internate" => "62%",
            "facebook" => "42%",
            "internate_user" => "32%",
            "linkedin" => "19%",
            "twitter" => "7%",
            "cid" => "3"
        ],
        [
            "id" => "100",
            "country" => "Grenada",
            "pop" => "0.1",
            "literacy" => "99%",
            "internate" => "80%",
            "facebook" => "40%",
            "internate_user" => "48%",
            "linkedin" => "48%",
            "twitter" => "7%",
            "cid" => "3"
        ],
        [
            "id" => "101",
            "country" => "Guatemala",
            "pop" => "18.7",
            "literacy" => "81%",
            "internate" => "53%",
            "facebook" => "33%",
            "internate_user" => "22%",
            "linkedin" => "11%",
            "twitter" => "4%",
            "cid" => "3"
        ],
        [
            "id" => "102",
            "country" => "Haiti",
            "pop" => "11.9",
            "literacy" => "62%",
            "internate" => "38%",
            "facebook" => "5%",
            "internate_user" => "4%",
            "linkedin" => "4%",
            "twitter" => "1%",
            "cid" => "3"
        ],
        [
            "id" => "103",
            "country" => "Honduras",
            "pop" => "11.0",
            "literacy" => "89%",
            "internate" => "58%",
            "facebook" => "25%",
            "internate_user" => "20%",
            "linkedin" => "10%",
            "twitter" => "3%",
            "cid" => "3"
        ],
        [
            "id" => "104",
            "country" => "Jamaica",
            "pop" => "2.8",
            "literacy" => "89%",
            "internate" => "85%",
            "facebook" => "19%",
            "internate_user" => "38%",
            "linkedin" => "35%",
            "twitter" => "7%",
            "cid" => "3"
        ],
        [
            "id" => "105",
            "country" => "Mexico",
            "pop" => "131.9",
            "literacy" => "95%",
            "internate" => "80%",
            "facebook" => "49%",
            "internate_user" => "41%",
            "linkedin" => "23%",
            "twitter" => "9%",
            "cid" => "3"
        ],
        [
            "id" => "106",
            "country" => "Nicaragua",
            "pop" => "7.0",
            "literacy" => "83%",
            "internate" => "60%",
            "facebook" => "26%",
            "internate_user" => "20%",
            "linkedin" => "12%",
            "twitter" => "2%",
            "cid" => "3"
        ],
        [
            "id" => "107",
            "country" => "Panama",
            "pop" => "4.6",
            "literacy" => "96%",
            "internate" => "72%",
            "facebook" => "31%",
            "internate_user" => "59%",
            "linkedin" => "37%",
            "twitter" => "7%",
            "cid" => "3"
        ],
        [
            "id" => "108",
            "country" => "Saint Kitts and Nevis",
            "pop" => "0.0",
            "literacy" => "97%",
            "internate" => "76%",
            "facebook" => "50%",
            "internate_user" => "61%",
            "linkedin" => "60%",
            "twitter" => "14%",
            "cid" => "3"
        ],
        [
            "id" => "109",
            "country" => "Saint Lucia",
            "pop" => "0.2",
            "literacy" => "90%",
            "internate" => "74%",
            "facebook" => "35%",
            "internate_user" => "40%",
            "linkedin" => "44%",
            "twitter" => "7%",
            "cid" => "3"
        ],
        [
            "id" => "110",
            "country" => "Saint Vincent and the Grenadines",
            "pop" => "0.1",
            "literacy" => "96%",
            "internate" => "79%",
            "facebook" => "45%",
            "internate_user" => "52%",
            "linkedin" => "42%",
            "twitter" => "8%",
            "cid" => "3"
        ],
        [
            "id" => "111",
            "country" => "The Bahamas",
            "pop" => "0.4",
            "literacy" => "96%",
            "internate" => "94%",
            "facebook" => "47%",
            "internate_user" => "33%",
            "linkedin" => "60%",
            "twitter" => "13%",
            "cid" => "3"
        ],
        [
            "id" => "112",
            "country" => "Trinidad and Tobago",
            "pop" => "1.5",
            "literacy" => "99%",
            "internate" => "80%",
            "facebook" => "39%",
            "internate_user" => "49%",
            "linkedin" => "48%",
            "twitter" => "7%",
            "cid" => "3"
        ],
        [
            "id" => "113",
            "country" => "Albania",
            "pop" => "2.8",
            "literacy" => "98%",
            "internate" => "84%",
            "facebook" => "34%",
            "internate_user" => "47%",
            "linkedin" => "27%",
            "twitter" => "4%",
            "cid" => "4"
        ],
        [
            "id" => "114",
            "country" => "Andorra",
            "pop" => "0.1",
            "literacy" => "100%",
            "internate" => "93%",
            "facebook" => "30%",
            "internate_user" => "58%",
            "linkedin" => "92%",
            "twitter" => "19%",
            "cid" => "4"
        ],
        [
            "id" => "115",
            "country" => "Austria",
            "pop" => "9.1",
            "literacy" => "98%",
            "internate" => "95%",
            "facebook" => "27%",
            "internate_user" => "38%",
            "linkedin" => "34%",
            "twitter" => "8%",
            "cid" => "4"
        ],
        [
            "id" => "116",
            "country" => "Belarus",
            "pop" => "9.0",
            "literacy" => "100%",
            "internate" => "92%",
            "facebook" => "3%",
            "internate_user" => "42%",
            "linkedin" => "12%",
            "twitter" => "1%",
            "cid" => "4"
        ],
        [
            "id" => "117",
            "country" => "Belgium",
            "pop" => "11.8",
            "literacy" => "99%",
            "internate" => "94%",
            "facebook" => "45%",
            "internate_user" => "45%",
            "linkedin" => "54%",
            "twitter" => "8%",
            "cid" => "4"
        ],
        [
            "id" => "118",
            "country" => "Bosnia and Herzegovina",
            "pop" => "3.1",
            "literacy" => "99%",
            "internate" => "84%",
            "facebook" => "35%",
            "internate_user" => "38%",
            "linkedin" => "17%",
            "twitter" => "3%",
            "cid" => "4"
        ],
        [
            "id" => "119",
            "country" => "Bulgaria",
            "pop" => "6.7",
            "literacy" => "98%",
            "internate" => "81%",
            "facebook" => "45%",
            "internate_user" => "30%",
            "linkedin" => "25%",
            "twitter" => "5%",
            "cid" => "4"
        ],
        [
            "id" => "120",
            "country" => "Croatia",
            "pop" => "3.8",
            "literacy" => "99%",
            "internate" => "84%",
            "facebook" => "42%",
            "internate_user" => "40%",
            "linkedin" => "31%",
            "twitter" => "5%",
            "cid" => "4"
        ],
        [
            "id" => "121",
            "country" => "Cyprus",
            "pop" => "1.4",
            "literacy" => "99%",
            "internate" => "90%",
            "facebook" => "48%",
            "internate_user" => "63%",
            "linkedin" => "47%",
            "twitter" => "9%",
            "cid" => "4"
        ],
        [
            "id" => "122",
            "country" => "Czech Republic",
            "pop" => "10.6",
            "literacy" => "99%",
            "internate" => "87%",
            "facebook" => "39%",
            "internate_user" => "39%",
            "linkedin" => "31%",
            "twitter" => "5%",
            "cid" => "4"
        ],
        [
            "id" => "123",
            "country" => "Denmark",
            "pop" => "6.0",
            "literacy" => "99%",
            "internate" => "98%",
            "facebook" => "49%",
            "internate_user" => "45%",
            "linkedin" => "65%",
            "twitter" => "8%",
            "cid" => "4"
        ],
        [
            "id" => "124",
            "country" => "Estonia",
            "pop" => "1.3",
            "literacy" => "100%",
            "internate" => "95%",
            "facebook" => "42%",
            "internate_user" => "38%",
            "linkedin" => "39%",
            "twitter" => "8%",
            "cid" => "4"
        ],
        [
            "id" => "125",
            "country" => "Finland",
            "pop" => "5.6",
            "literacy" => "100%",
            "internate" => "93%",
            "facebook" => "33%",
            "internate_user" => "43%",
            "linkedin" => "43%",
            "twitter" => "124%",
            "cid" => "4"
        ],
        [
            "id" => "126",
            "country" => "France",
            "pop" => "66.7",
            "literacy" => "99%",
            "internate" => "87%",
            "facebook" => "38%",
            "internate_user" => "44%",
            "linkedin" => "59%",
            "twitter" => "11%",
            "cid" => "4"
        ],
        [
            "id" => "127",
            "country" => "Germany",
            "pop" => "84.1",
            "literacy" => "99%",
            "internate" => "93%",
            "facebook" => "21%",
            "internate_user" => "39%",
            "linkedin" => "30%",
            "twitter" => "12%",
            "cid" => "4"
        ],
        [
            "id" => "128",
            "country" => "Greece",
            "pop" => "9.9",
            "literacy" => "98%",
            "internate" => "87%",
            "facebook" => "43%",
            "internate_user" => "47%",
            "linkedin" => "32%",
            "twitter" => "6%",
            "cid" => "4"
        ],
        [
            "id" => "129",
            "country" => "Hungary",
            "pop" => "9.6",
            "literacy" => "99%",
            "internate" => "92%",
            "facebook" => "50%",
            "internate_user" => "31%",
            "linkedin" => "22%",
            "twitter" => "4%",
            "cid" => "4"
        ],
        [
            "id" => "130",
            "country" => "Iceland",
            "pop" => "0.4",
            "literacy" => "99%",
            "internate" => "98%",
            "facebook" => "52%",
            "internate_user" => "52%",
            "linkedin" => "78%",
            "twitter" => "16%",
            "cid" => "4"
        ],
        [
            "id" => "131",
            "country" => "Ireland",
            "pop" => "5.3",
            "literacy" => "99%",
            "internate" => "94%",
            "facebook" => "40%",
            "internate_user" => "51%",
            "linkedin" => "72%",
            "twitter" => "17%",
            "cid" => "4"
        ],
        [
            "id" => "132",
            "country" => "Italy",
            "pop" => "59.1",
            "literacy" => "99%",
            "internate" => "87%",
            "facebook" => "40%",
            "internate_user" => "51%",
            "linkedin" => "44%",
            "twitter" => "4%",
            "cid" => "4"
        ],
        [
            "id" => "133",
            "country" => "Latvia",
            "pop" => "1.9",
            "literacy" => "100%",
            "internate" => "93%",
            "facebook" => "39%",
            "internate_user" => "40%",
            "linkedin" => "37%",
            "twitter" => "10%",
            "cid" => "4"
        ],
        [
            "id" => "134",
            "country" => "Liechtenstein",
            "pop" => "0.0",
            "literacy" => "100%",
            "internate" => "96%",
            "facebook" => "18%",
            "internate_user" => "30%",
            "linkedin" => "72%",
            "twitter" => "5%",
            "cid" => "4"
        ],
        [
            "id" => "135",
            "country" => "Lithuania",
            "pop" => "2.8",
            "literacy" => "100%",
            "internate" => "90%",
            "facebook" => "53%",
            "internate_user" => "36%",
            "linkedin" => "35%",
            "twitter" => "8%",
            "cid" => "4"
        ],
        [
            "id" => "136",
            "country" => "Luxembourg",
            "pop" => "0.7",
            "literacy" => "100%",
            "internate" => "98%",
            "facebook" => "39%",
            "internate_user" => "45%",
            "linkedin" => "73%",
            "twitter" => "18%",
            "cid" => "4"
        ],
        [
            "id" => "137",
            "country" => "Malta",
            "pop" => "0.5",
            "literacy" => "95%",
            "internate" => "90%",
            "facebook" => "63%",
            "internate_user" => "52%",
            "linkedin" => "75%",
            "twitter" => "9%",
            "cid" => "4"
        ],
        [
            "id" => "138",
            "country" => "Moldova",
            "pop" => "3.0",
            "literacy" => "99%",
            "internate" => "65%",
            "facebook" => "38%",
            "internate_user" => "37%",
            "linkedin" => "18%",
            "twitter" => "2%",
            "cid" => "4"
        ],
        [
            "id" => "139",
            "country" => "Monaco",
            "pop" => "0.0",
            "literacy" => "99%",
            "internate" => "99%",
            "facebook" => "17%",
            "internate_user" => "33%",
            "linkedin" => "162%",
            "twitter" => "15%",
            "cid" => "4"
        ],
        [
            "id" => "140",
            "country" => "Montenegro",
            "pop" => "0.6",
            "literacy" => "99%",
            "internate" => "89%",
            "facebook" => "39%",
            "internate_user" => "67%",
            "linkedin" => "28%",
            "twitter" => "6%",
            "cid" => "4"
        ],
        [
            "id" => "141",
            "country" => "Netherlands",
            "pop" => "18.3",
            "literacy" => "99%",
            "internate" => "96%",
            "facebook" => "32%",
            "internate_user" => "46%",
            "linkedin" => "76%",
            "twitter" => "21%",
            "cid" => "4"
        ],
        [
            "id" => "142",
            "country" => "North Macedonia",
            "pop" => "1.8",
            "literacy" => "98%",
            "internate" => "85%",
            "facebook" => "42%",
            "internate_user" => "48%",
            "linkedin" => "26%",
            "twitter" => "4%",
            "cid" => "4"
        ],
        [
            "id" => "143",
            "country" => "Norway",
            "pop" => "5.6",
            "literacy" => "100%",
            "internate" => "98%",
            "facebook" => "47%",
            "internate_user" => "48%",
            "linkedin" => "57%",
            "twitter" => "10%",
            "cid" => "4"
        ],
        [
            "id" => "144",
            "country" => "Poland",
            "pop" => "38.1",
            "literacy" => "100%",
            "internate" => "88%",
            "facebook" => "42%",
            "internate_user" => "34%",
            "linkedin" => "25%",
            "twitter" => "7%",
            "cid" => "4"
        ],
        [
            "id" => "145",
            "country" => "Portugal",
            "pop" => "10.4",
            "literacy" => "96%",
            "internate" => "86%",
            "facebook" => "50%",
            "internate_user" => "62%",
            "linkedin" => "60%",
            "twitter" => "9%",
            "cid" => "4"
        ],
        [
            "id" => "146",
            "country" => "Romania",
            "pop" => "18.9",
            "literacy" => "99%",
            "internate" => "90%",
            "facebook" => "48%",
            "internate_user" => "32%",
            "linkedin" => "29%",
            "twitter" => "4%",
            "cid" => "4"
        ],
        [
            "id" => "147",
            "country" => "San Marino",
            "pop" => "0.0",
            "literacy" => "100%",
            "internate" => "85%",
            "facebook" => "15%",
            "internate_user" => "21%",
            "linkedin" => "51%",
            "twitter" => "3%",
            "cid" => "4"
        ],
        [
            "id" => "148",
            "country" => "Serbia",
            "pop" => "6.7",
            "literacy" => "100%",
            "internate" => "86%",
            "facebook" => "33%",
            "internate_user" => "51%",
            "linkedin" => "27%",
            "twitter" => "6%",
            "cid" => "4"
        ],
        [
            "id" => "149",
            "country" => "Slovakia",
            "pop" => "5.5",
            "literacy" => "100%",
            "internate" => "88%",
            "facebook" => "39%",
            "internate_user" => "34%",
            "linkedin" => "20%",
            "twitter" => "3%",
            "cid" => "4"
        ],
        [
            "id" => "150",
            "country" => "Slovenia",
            "pop" => "2.1",
            "literacy" => "100%",
            "internate" => "90%",
            "facebook" => "39%",
            "internate_user" => "35%",
            "linkedin" => "31%",
            "twitter" => "5%",
            "cid" => "4"
        ],
        [
            "id" => "151",
            "country" => "Spain",
            "pop" => "47.9",
            "literacy" => "99%",
            "internate" => "96%",
            "facebook" => "34%",
            "internate_user" => "58%",
            "linkedin" => "52%",
            "twitter" => "13%",
            "cid" => "4"
        ],
        [
            "id" => "152",
            "country" => "Sweden",
            "pop" => "10.7",
            "literacy" => "99%",
            "internate" => "95%",
            "facebook" => "44%",
            "internate_user" => "54%",
            "linkedin" => "60%",
            "twitter" => "9%",
            "cid" => "4"
        ],
        [
            "id" => "153",
            "country" => "Switzerland",
            "pop" => "9.0",
            "literacy" => "99%",
            "internate" => "97%",
            "facebook" => "26%",
            "internate_user" => "44%",
            "linkedin" => "60%",
            "twitter" => "13%",
            "cid" => "4"
        ],
        [
            "id" => "154",
            "country" => "Ukraine",
            "pop" => "39.0",
            "literacy" => "100%",
            "internate" => "76%",
            "facebook" => "23%",
            "internate_user" => "31%",
            "linkedin" => "17%",
            "twitter" => "2%",
            "cid" => "4"
        ],
        [
            "id" => "155",
            "country" => "United Kingdom",
            "pop" => "69.6",
            "literacy" => "99%",
            "internate" => "94%",
            "facebook" => "44%",
            "internate_user" => "51%",
            "linkedin" => "70%",
            "twitter" => "17%",
            "cid" => "4"
        ],
        [
            "id" => "156",
            "country" => "Vatican",
            "pop" => "0.0",
            "literacy" => "99%",
            "internate" => "162%",
            "facebook" => "100%",
            "internate_user" => "100%",
            "linkedin" => "1337%",
            "twitter" => "319%",
            "cid" => "4"
        ],
        [
            "id" => "157",
            "country" => "Canada",
            "pop" => "40.1",
            "literacy" => "99%",
            "internate" => "93%",
            "facebook" => "46%",
            "internate_user" => "51%",
            "linkedin" => "72%",
            "twitter" => "15%",
            "cid" => "5"
        ],
        [
            "id" => "158",
            "country" => "United States of America",
            "pop" => "347.3",
            "literacy" => "86%",
            "internate" => "96%",
            "facebook" => "44%",
            "internate_user" => "51%",
            "linkedin" => "78%",
            "twitter" => "20%",
            "cid" => "5"
        ],
        [
            "id" => "159",
            "country" => "Argentina",
            "pop" => "45.9",
            "literacy" => "99%",
            "internate" => "89%",
            "facebook" => "34%",
            "internate_user" => "66%",
            "linkedin" => "41%",
            "twitter" => "11%",
            "cid" => "6"
        ],
        [
            "id" => "160",
            "country" => "Bolivia",
            "pop" => "12.6",
            "literacy" => "93%",
            "internate" => "72%",
            "facebook" => "28%",
            "internate_user" => "20%",
            "linkedin" => "17%",
            "twitter" => "2%",
            "cid" => "6"
        ],
        [
            "id" => "161",
            "country" => "Brazil",
            "pop" => "212.8",
            "literacy" => "93%",
            "internate" => "84%",
            "facebook" => "39%",
            "internate_user" => "69%",
            "linkedin" => "44%",
            "twitter" => "6%",
            "cid" => "6"
        ],
        [
            "id" => "162",
            "country" => "Chile",
            "pop" => "19.9",
            "literacy" => "96%",
            "internate" => "93%",
            "facebook" => "49%",
            "internate_user" => "69%",
            "linkedin" => "50%",
            "twitter" => "11%",
            "cid" => "6"
        ],
        [
            "id" => "163",
            "country" => "Colombia",
            "pop" => "53.4",
            "literacy" => "96%",
            "internate" => "72%",
            "facebook" => "39%",
            "internate_user" => "40%",
            "linkedin" => "36%",
            "twitter" => "6%",
            "cid" => "6"
        ],
        [
            "id" => "164",
            "country" => "Ecuador",
            "pop" => "18.3",
            "literacy" => "94%",
            "internate" => "72%",
            "facebook" => "39%",
            "internate_user" => "38%",
            "linkedin" => "33%",
            "twitter" => "6%",
            "cid" => "6"
        ],
        [
            "id" => "165",
            "country" => "Guyana",
            "pop" => "0.8",
            "literacy" => "89%",
            "internate" => "85%",
            "facebook" => "44%",
            "internate_user" => "24%",
            "linkedin" => "23%",
            "twitter" => "3%",
            "cid" => "6"
        ],
        [
            "id" => "166",
            "country" => "Paraguay",
            "pop" => "7.0",
            "literacy" => "95%",
            "internate" => "77%",
            "facebook" => "32%",
            "internate_user" => "41%",
            "linkedin" => "21%",
            "twitter" => "5%",
            "cid" => "6"
        ],
        [
            "id" => "167",
            "country" => "Peru",
            "pop" => "34.6",
            "literacy" => "95%",
            "internate" => "74%",
            "facebook" => "44%",
            "internate_user" => "33%",
            "linkedin" => "38%",
            "twitter" => "4%",
            "cid" => "6"
        ],
        [
            "id" => "168",
            "country" => "Suriname",
            "pop" => "0.6",
            "literacy" => "94%",
            "internate" => "75%",
            "facebook" => "37%",
            "internate_user" => "20%",
            "linkedin" => "23%",
            "twitter" => "3%",
            "cid" => "6"
        ],
        [
            "id" => "169",
            "country" => "Venezuela",
            "pop" => "28.5",
            "literacy" => "97%",
            "internate" => "61%",
            "facebook" => "12%",
            "internate_user" => "35%",
            "linkedin" => "23%",
            "twitter" => "1%",
            "cid" => "6"
        ],
        [
            "id" => "170",
            "country" => "Uruguay",
            "pop" => "3.4",
            "literacy" => "99%",
            "internate" => "90%",
            "facebook" => "41%",
            "internate_user" => "71%",
            "linkedin" => "53%",
            "twitter" => "13%",
            "cid" => "6"
        ],
        [
            "id" => "171",
            "country" => "Brunei",
            "pop" => "0.5",
            "literacy" => "97%",
            "internate" => "98%",
            "facebook" => "36%",
            "internate_user" => "64%",
            "linkedin" => "34%",
            "twitter" => "11%",
            "cid" => "7"
        ],
        [
            "id" => "172",
            "country" => "Cambodia",
            "pop" => "17.8",
            "literacy" => "81%",
            "internate" => "56%",
            "facebook" => "52%",
            "internate_user" => "10%",
            "linkedin" => "5%",
            "twitter" => "2%",
            "cid" => "7"
        ],
        [
            "id" => "173",
            "country" => "Australia",
            "pop" => "27.0",
            "literacy" => "99%",
            "internate" => "93%",
            "facebook" => "53%",
            "internate_user" => "57%",
            "linkedin" => "67%",
            "twitter" => "12%",
            "cid" => "7"
        ],
        [
            "id" => "174",
            "country" => "East Timor",
            "pop" => "1.4",
            "literacy" => "68%",
            "internate" => "40%",
            "facebook" => "7%",
            "internate_user" => "6%",
            "linkedin" => "4%",
            "twitter" => "0%",
            "cid" => "7"
        ],
        [
            "id" => "175",
            "country" => "Federated States of Micronesia",
            "pop" => "0.1",
            "literacy" => "99%",
            "internate" => "40%",
            "facebook" => "23%",
            "internate_user" => "11%",
            "linkedin" => "12%",
            "twitter" => "1%",
            "cid" => "7"
        ],
        [
            "id" => "176",
            "country" => "Fiji",
            "pop" => "0.9",
            "literacy" => "99%",
            "internate" => "85%",
            "facebook" => "38%",
            "internate_user" => "31%",
            "linkedin" => "31%",
            "twitter" => "2%",
            "cid" => "7"
        ],
        [
            "id" => "177",
            "country" => "Indonesia",
            "pop" => "285.7",
            "literacy" => "96%",
            "internate" => "68%",
            "facebook" => "17%",
            "internate_user" => "39%",
            "linkedin" => "14%",
            "twitter" => "6%",
            "cid" => "7"
        ],
        [
            "id" => "178",
            "country" => "Kiribati",
            "pop" => "0.1",
            "literacy" => "93%",
            "internate" => "53%",
            "facebook" => "22%",
            "internate_user" => "4%",
            "linkedin" => "10%",
            "twitter" => "0%",
            "cid" => "7"
        ],
        [
            "id" => "179",
            "country" => "Laos",
            "pop" => "7.9",
            "literacy" => "85%",
            "internate" => "65%",
            "facebook" => "37%",
            "internate_user" => "7%",
            "linkedin" => "3%",
            "twitter" => "2%",
            "cid" => "7"
        ],
        [
            "id" => "180",
            "country" => "Malaysia",
            "pop" => "36.0",
            "literacy" => "95%",
            "internate" => "96%",
            "facebook" => "51%",
            "internate_user" => "44%",
            "linkedin" => "28%",
            "twitter" => "9%",
            "cid" => "7"
        ],
        [
            "id" => "181",
            "country" => "Marshall Islands",
            "pop" => "0.0",
            "literacy" => "98%",
            "internate" => "77%",
            "facebook" => "44%",
            "internate_user" => "16%",
            "linkedin" => "33%",
            "twitter" => "0%",
            "cid" => "7"
        ],
        [
            "id" => "182",
            "country" => "Myanmar",
            "pop" => "54.9",
            "literacy" => "89%",
            "internate" => "44%",
            "facebook" => "13%",
            "internate_user" => "1%",
            "linkedin" => "2%",
            "twitter" => "0%",
            "cid" => "7"
        ],
        [
            "id" => "183",
            "country" => "Nauru",
            "pop" => "0.0",
            "literacy" => "95%",
            "internate" => "82%",
            "facebook" => "52%",
            "internate_user" => "31%",
            "linkedin" => "61%",
            "twitter" => "3%",
            "cid" => "7"
        ],
        [
            "id" => "184",
            "country" => "New Zealand",
            "pop" => "5.3",
            "literacy" => "99%",
            "internate" => "95%",
            "facebook" => "52%",
            "internate_user" => "50%",
            "linkedin" => "65%",
            "twitter" => "8%",
            "cid" => "7"
        ],
        [
            "id" => "185",
            "country" => "Palau",
            "pop" => "0.0",
            "literacy" => "97%",
            "internate" => "66%",
            "facebook" => "65%",
            "internate_user" => "38%",
            "linkedin" => "57%",
            "twitter" => "7%",
            "cid" => "7"
        ],
        [
            "id" => "186",
            "country" => "Papua New Guinea",
            "pop" => "10.8",
            "literacy" => "64%",
            "internate" => "26%",
            "facebook" => "1%",
            "internate_user" => "1%",
            "linkedin" => "6%",
            "twitter" => "0%",
            "cid" => "7"
        ],
        [
            "id" => "187",
            "country" => "Philippines",
            "pop" => "116.8",
            "literacy" => "96%",
            "internate" => "74%",
            "facebook" => "48%",
            "internate_user" => "23%",
            "linkedin" => "20%",
            "twitter" => "4%",
            "cid" => "7"
        ],
        [
            "id" => "188",
            "country" => "Samoa",
            "pop" => "0.2",
            "literacy" => "99%",
            "internate" => "75%",
            "facebook" => "27%",
            "internate_user" => "22%",
            "linkedin" => "11%",
            "twitter" => "1%",
            "cid" => "7"
        ],
        [
            "id" => "189",
            "country" => "Singapore",
            "pop" => "5.9",
            "literacy" => "98%",
            "internate" => "93%",
            "facebook" => "51%",
            "internate_user" => "92%",
            "linkedin" => "90%",
            "twitter" => "61%",
            "cid" => "7"
        ],
        [
            "id" => "190",
            "country" => "Solomon Islands",
            "pop" => "0.8",
            "literacy" => "77%",
            "internate" => "43%",
            "facebook" => "3%",
            "internate_user" => "27%",
            "linkedin" => "4%",
            "twitter" => "0%",
            "cid" => "7"
        ],
        [
            "id" => "191",
            "country" => "Thailand",
            "pop" => "71.6",
            "literacy" => "94%",
            "internate" => "90%",
            "facebook" => "18%",
            "internate_user" => "79%",
            "linkedin" => "9%",
            "twitter" => "13%",
            "cid" => "7"
        ],
        [
            "id" => "192",
            "country" => "Tonga",
            "pop" => "0.1",
            "literacy" => "99%",
            "internate" => "58%",
            "facebook" => "42%",
            "internate_user" => "71%",
            "linkedin" => "17%",
            "twitter" => "1%",
            "cid" => "7"
        ],
        [
            "id" => "193",
            "country" => "Tuvalu",
            "pop" => "0.0",
            "literacy" => "99%",
            "internate" => "83%",
            "facebook" => "50%",
            "internate_user" => "70%",
            "linkedin" => "43%",
            "twitter" => "1%",
            "cid" => "7"
        ],
        [
            "id" => "194",
            "country" => "Vanuatu",
            "pop" => "0.3",
            "literacy" => "88%",
            "internate" => "68%",
            "facebook" => "11%",
            "internate_user" => "46%",
            "linkedin" => "8%",
            "twitter" => "0%",
            "cid" => "7"
        ],
        [
            "id" => "195",
            "country" => "Vietnam",
            "pop" => "101.6",
            "literacy" => "96%",
            "internate" => "77%",
            "facebook" => "59%",
            "internate_user" => "79%",
            "linkedin" => "11%",
            "twitter" => "5%",
            "cid" => "7"
        ]
    ],
    'cid' => [
        '1' => 'Africa',
        '2' => 'Asia',
        '3' => 'Central America and the Caribbean',
        '4' => 'Europe',
        '5' => 'North America',
        '6' => 'South America',
        '7' => 'South East Asia and Oceania'
    ]
];
