<?php

return [
    'languages' => [
        ['no' => 1,  'language' => 'Afrikaans', 'language_id' => 1,  'country' => 'South Africa'],
        ['no' => 2,  'language' => 'Albanian',  'language_id' => 2,  'country' => 'Albania'],
        ['no' => 3,  'language' => 'Albanian',  'language_id' => 2,  'country' => 'North Macedonia'],

        ['no' => 4,  'language' => 'Arabic', 'language_id' => 3, 'country' => 'Algeria'],
        ['no' => 5,  'language' => 'Arabic', 'language_id' => 3, 'country' => 'Bahrain'],
        ['no' => 6,  'language' => 'Arabic', 'language_id' => 3, 'country' => 'Chad'],
        ['no' => 7,  'language' => 'Arabic', 'language_id' => 3, 'country' => 'Djibouti'],
        ['no' => 8,  'language' => 'Arabic', 'language_id' => 3, 'country' => 'Egypt'],
        ['no' => 9,  'language' => 'Arabic', 'language_id' => 3, 'country' => 'Iraq'],
        ['no' => 10, 'language' => 'Arabic', 'language_id' => 3, 'country' => 'Jordan'],
        ['no' => 11, 'language' => 'Arabic', 'language_id' => 3, 'country' => 'Lebanon'],
        ['no' => 12, 'language' => 'Arabic', 'language_id' => 3, 'country' => 'Libya'],
        ['no' => 13, 'language' => 'Arabic', 'language_id' => 3, 'country' => 'Mauritania'],
        ['no' => 14, 'language' => 'Arabic', 'language_id' => 3, 'country' => 'Morocco'],
        ['no' => 15, 'language' => 'Arabic', 'language_id' => 3, 'country' => 'Oman'],
        ['no' => 16, 'language' => 'Arabic', 'language_id' => 3, 'country' => 'Palestine'],
        ['no' => 17, 'language' => 'Arabic', 'language_id' => 3, 'country' => 'Qatar'],
        ['no' => 18, 'language' => 'Arabic', 'language_id' => 3, 'country' => 'Saudi Arabia'],
        ['no' => 19, 'language' => 'Arabic', 'language_id' => 3, 'country' => 'Sudan'],
        ['no' => 20, 'language' => 'Arabic', 'language_id' => 3, 'country' => 'Syria'],
        ['no' => 21, 'language' => 'Arabic', 'language_id' => 3, 'country' => 'Tunisia'],
        ['no' => 22, 'language' => 'Arabic', 'language_id' => 3, 'country' => 'United Arab Emirates'],
        ['no' => 23, 'language' => 'Arabic', 'language_id' => 3, 'country' => 'Yemen'],
        ['no' => 24, 'language' => 'Arabic', 'language_id' => 3, 'country' => 'Kuwait'],
        ['no' => 25, 'language' => 'Arabic', 'language_id' => 3, 'country' => 'Somalia'],
        ['no' => 26, 'language' => 'Arabic', 'language_id' => 3, 'country' => 'Comoros'],

        ['no' => 27, 'language' => 'Araona', 'language_id' => 4, 'country' => 'Bolivia'],
        ['no' => 28, 'language' => 'Armenian', 'language_id' => 5, 'country' => 'Armenia'],
        ['no' => 29, 'language' => 'Ashaninka', 'language_id' => 6, 'country' => 'Peru'],
        ['no' => 30, 'language' => 'Assamese', 'language_id' => 7, 'country' => 'India'],
        ['no' => 31, 'language' => 'Aymara', 'language_id' => 8, 'country' => 'Bolivia'],
        ['no' => 32, 'language' => 'Azerbaijani', 'language_id' => 9, 'country' => 'Azerbaijan'],
        ['no' => 33, 'language' => 'Bambara', 'language_id' => 10, 'country' => 'Mali'],
        ['no' => 34, 'language' => 'Baure', 'language_id' => 11, 'country' => 'Bolivia'],
        ['no' => 35, 'language' => 'Belurusian', 'language_id' => 12, 'country' => 'Belarus'],

        ['no' => 36, 'language' => 'Bengali', 'language_id' => 13, 'country' => 'Bangladesh'],
        ['no' => 37, 'language' => 'Bengali', 'language_id' => 13, 'country' => 'India'],
        ['no' => 38, 'language' => 'Bengali', 'language_id' => 13, 'country' => 'Saudi Arabia'],
        ['no' => 39, 'language' => 'Bengali', 'language_id' => 13, 'country' => 'United Arab Emirates'],

        ['no' => 40, 'language' => 'Berber', 'language_id' => 14, 'country' => 'Morocco'],
        ['no' => 41, 'language' => 'Berber', 'language_id' => 14, 'country' => 'Algeria'],

        ['no' => 42, 'language' => 'Besiro (Chiquitano)', 'language_id' => 15, 'country' => 'Bolivia'],
        ['no' => 43, 'language' => 'Bislama', 'language_id' => 16, 'country' => 'Vanuatu'],
        ['no' => 44, 'language' => 'Bobo', 'language_id' => 17, 'country' => 'Mali'],
        ['no' => 45, 'language' => 'Bosnian', 'language_id' => 18, 'country' => 'Bosnia and Herzegovina'],
        ['no' => 46, 'language' => 'Bozo', 'language_id' => 19, 'country' => 'Mali'],
        ['no' => 47, 'language' => 'Bulgarian', 'language_id' => 20, 'country' => 'Bulgaria'],
        ['no' => 48, 'language' => 'Burmese', 'language_id' => 21, 'country' => 'Myanmar'],

        ['no' => 49, 'language' => 'Canichana', 'language_id' => 22, 'country' => 'Bolivia'],
        ['no' => 50, 'language' => 'Catalan', 'language_id' => 23, 'country' => 'Andorra'],
        ['no' => 51, 'language' => 'Cavinena', 'language_id' => 24, 'country' => 'Bolivia'],
        ['no' => 52, 'language' => 'Cayubaba', 'language_id' => 25, 'country' => 'Bolivia'],
        ['no' => 53, 'language' => 'Chacobo', 'language_id' => 26, 'country' => 'Bolivia'],
        ['no' => 54, 'language' => 'Chichewa', 'language_id' => 27, 'country' => 'Zimbabwe'],
        ['no' => 55, 'language' => 'Chibarwe', 'language_id' => 28, 'country' => 'Zimbabwe'],
        ['no' => 56, 'language' => 'Chilian', 'language_id' => 29, 'country' => 'Chile'],
        ['no' => 57, 'language' => 'Chiman', 'language_id' => 30, 'country' => 'Bolivia'],
        ['no' => 58, 'language' => 'Comorian', 'language_id' => 31, 'country' => 'Comoros'],

        ['no' => 59, 'language' => 'Croatian', 'language_id' => 32, 'country' => 'Croatia'],
        ['no' => 60, 'language' => 'Croatian', 'language_id' => 32, 'country' => 'Bosnia and Herzegovina'],
        ['no' => 61, 'language' => 'Czech', 'language_id' => 33, 'country' => 'Czech Republic'],
        ['no' => 62, 'language' => 'Danish', 'language_id' => 34, 'country' => 'Denmark'],
        ['no' => 63, 'language' => 'Dhivehi', 'language_id' => 35, 'country' => 'Maldives'],
        ['no' => 64, 'language' => 'Dogon', 'language_id' => 36, 'country' => 'Mali'],
        ['no' => 65, 'language' => 'Dutch', 'language_id' => 37, 'country' => 'Belgium'],
        ['no' => 66, 'language' => 'Dutch', 'language_id' => 37, 'country' => 'Netherlands'],
        ['no' => 67, 'language' => 'Dutch', 'language_id' => 37, 'country' => 'Suriname'],
        ['no' => 68, 'language' => 'Dzongkha', 'language_id' => 38, 'country' => 'Bhutan'],
        ['no' => 69, 'language' => 'English', 'language_id' => 39, 'country' => 'Antigua and Barbuda'],
        ['no' => 70, 'language' => 'English', 'language_id' => 39, 'country' => 'Australia'],
        ['no' => 71, 'language' => 'English', 'language_id' => 39, 'country' => 'Barbados'],
        ['no' => 72, 'language' => 'English', 'language_id' => 39, 'country' => 'Belize'],
        ['no' => 73, 'language' => 'English', 'language_id' => 39, 'country' => 'Botswana'],
        ['no' => 74, 'language' => 'English', 'language_id' => 39, 'country' => 'Dominica'],
        ['no' => 75, 'language' => 'English', 'language_id' => 39, 'country' => 'Federated States of Micronesia'],
        ['no' => 76, 'language' => 'English', 'language_id' => 39, 'country' => 'Gambia'],
        ['no' => 77, 'language' => 'English', 'language_id' => 39, 'country' => 'Ghana'],
        ['no' => 78, 'language' => 'English', 'language_id' => 39, 'country' => 'Grenada'],
        ['no' => 79, 'language' => 'English', 'language_id' => 39, 'country' => 'Guyana'],
        ['no' => 80, 'language' => 'English', 'language_id' => 39, 'country' => 'Ireland'],
        ['no' => 81, 'language' => 'English', 'language_id' => 39, 'country' => 'Jamaica'],
        ['no' => 82, 'language' => 'English', 'language_id' => 39, 'country' => 'Liberia'],
        ['no' => 83, 'language' => 'English', 'language_id' => 39, 'country' => 'Namibia'],
        ['no' => 84, 'language' => 'English', 'language_id' => 39, 'country' => 'New Zealand'],
        ['no' => 85, 'language' => 'English', 'language_id' => 39, 'country' => 'Nigeria'],
        ['no' => 86, 'language' => 'English', 'language_id' => 39, 'country' => 'Papua New Guinea'],
        ['no' => 87, 'language' => 'English', 'language_id' => 39, 'country' => 'Saint Kitts and Nevis'],
        ['no' => 88, 'language' => 'English', 'language_id' => 39, 'country' => 'Saint Lucia'],
        ['no' => 89, 'language' => 'English', 'language_id' => 39, 'country' => 'Saint Vincent and the Grenadines'],
        ['no' => 90, 'language' => 'English', 'language_id' => 39, 'country' => 'Sierra Leone'],
        ['no' => 91, 'language' => 'English', 'language_id' => 39, 'country' => 'Singapore'],
        ['no' => 92, 'language' => 'English', 'language_id' => 39, 'country' => 'Solomon Islands'],
        ['no' => 93, 'language' => 'English', 'language_id' => 39, 'country' => 'South Sudan'],
        ['no' => 94, 'language' => 'English', 'language_id' => 39, 'country' => 'The Bahamas'],
        ['no' => 95, 'language' => 'English', 'language_id' => 39, 'country' => 'Tonga'],
        ['no' => 96, 'language' => 'English', 'language_id' => 39, 'country' => 'Trinidad and Tobago'],
        ['no' => 97, 'language' => 'English', 'language_id' => 39, 'country' => 'Uganda'],
        ['no' => 98, 'language' => 'English', 'language_id' => 39, 'country' => 'United Kingdom'],
        ['no' => 99, 'language' => 'English', 'language_id' => 39, 'country' => 'United States of America'],
        ['no' => 100, 'language' => 'English', 'language_id' => 39, 'country' => 'Zambia'],
        ['no' => 101, 'language' => 'English', 'language_id' => 39, 'country' => 'Canada'],
        ['no' => 102, 'language' => 'English', 'language_id' => 39, 'country' => 'Sudan'],
        ['no' => 103, 'language' => 'English', 'language_id' => 39, 'country' => 'South Africa'],
        ['no' => 104, 'language' => 'English', 'language_id' => 39, 'country' => 'Cameroon'],
        ['no' => 105, 'language' => 'English', 'language_id' => 39, 'country' => 'India'],
        ['no' => 106, 'language' => 'English', 'language_id' => 39, 'country' => 'Lesotho'],
        ['no' => 107, 'language' => 'English', 'language_id' => 39, 'country' => 'Malta'],
        ['no' => 108, 'language' => 'English', 'language_id' => 39, 'country' => 'Marshall Islands'],
        ['no' => 109, 'language' => 'English', 'language_id' => 39, 'country' => 'Mauritius'],
        ['no' => 110, 'language' => 'English', 'language_id' => 39, 'country' => 'Nauru'],
        ['no' => 111, 'language' => 'English', 'language_id' => 39, 'country' => 'Pakistan'],
        ['no' => 112, 'language' => 'English', 'language_id' => 39, 'country' => 'Palau'],
        ['no' => 113, 'language' => 'English', 'language_id' => 39, 'country' => 'Philippines'],
        ['no' => 114, 'language' => 'English', 'language_id' => 39, 'country' => 'Samoa'],
        ['no' => 115, 'language' => 'English', 'language_id' => 39, 'country' => 'Swaziland'],
        ['no' => 116, 'language' => 'English', 'language_id' => 39, 'country' => 'Tanzania'],
        ['no' => 117, 'language' => 'English', 'language_id' => 39, 'country' => 'Tuvalu'],
        ['no' => 118, 'language' => 'English', 'language_id' => 39, 'country' => 'Kiribati'],
        ['no' => 119, 'language' => 'English', 'language_id' => 39, 'country' => 'Malawi'],
        ['no' => 120, 'language' => 'English', 'language_id' => 39, 'country' => 'Kenya'],
        ['no' => 121, 'language' => 'English', 'language_id' => 39, 'country' => 'Fiji'],
        ['no' => 122, 'language' => 'English', 'language_id' => 39, 'country' => 'Seychelles'],
        ['no' => 123, 'language' => 'English', 'language_id' => 39, 'country' => 'Vanuatu'],
        ['no' => 124, 'language' => 'English', 'language_id' => 39, 'country' => 'Rwanda'],
        ['no' => 125, 'language' => 'English', 'language_id' => 39, 'country' => 'Burundi'],
        ['no' => 126, 'language' => 'English', 'language_id' => 39, 'country' => 'Zimbabwe'],

        ['no' => 127, 'language' => 'Ese Ejja', 'language_id' => 40, 'country' => 'Bolivia'],
        ['no' => 128, 'language' => 'Estonian', 'language_id' => 41, 'country' => 'Estonia'],
        ['no' => 129, 'language' => 'Fiji Hindi', 'language_id' => 42, 'country' => 'Fiji'],
        ['no' => 130, 'language' => 'Fijian', 'language_id' => 43, 'country' => 'Fiji'],
        ['no' => 131, 'language' => 'Filipino', 'language_id' => 44, 'country' => 'Philippines'],
        ['no' => 132, 'language' => 'Finnish', 'language_id' => 45, 'country' => 'Finland'],
        ['no' => 133, 'language' => 'French', 'language_id' => 46, 'country' => 'Benin'],
        ['no' => 134, 'language' => 'French', 'language_id' => 46, 'country' => 'Burkina Faso'],
        ['no' => 135, 'language' => 'French', 'language_id' => 46, 'country' => 'Cameroon'],
        ['no' => 136, 'language' => 'French', 'language_id' => 46, 'country' => 'Democratic Republic of the Congo'],
        ['no' => 137, 'language' => 'French', 'language_id' => 46, 'country' => 'France'],
        ['no' => 138, 'language' => 'French', 'language_id' => 46, 'country' => 'Gabon'],
        ['no' => 139, 'language' => 'French', 'language_id' => 46, 'country' => 'Guinea'],
        ['no' => 140, 'language' => 'French', 'language_id' => 46, 'country' => 'Ivory Coast'],
        ['no' => 141, 'language' => 'French', 'language_id' => 46, 'country' => 'Luxembourg'],
        ['no' => 142, 'language' => 'French', 'language_id' => 46, 'country' => 'Madagascar'],
        ['no' => 143, 'language' => 'French', 'language_id' => 46, 'country' => 'Monaco'],
        ['no' => 144, 'language' => 'French', 'language_id' => 46, 'country' => 'Niger'],
        ['no' => 145, 'language' => 'French', 'language_id' => 46, 'country' => 'Republic of Congo'],
        ['no' => 146, 'language' => 'French', 'language_id' => 46, 'country' => 'Senegal'],
        ['no' => 147, 'language' => 'French', 'language_id' => 46, 'country' => 'Togo'],
        ['no' => 148, 'language' => 'French', 'language_id' => 46, 'country' => 'Djibouti'],
        ['no' => 149, 'language' => 'French', 'language_id' => 46, 'country' => 'Comoros'],
        ['no' => 150, 'language' => 'French', 'language_id' => 46, 'country' => 'Seychelles'],
        ['no' => 151, 'language' => 'French', 'language_id' => 46, 'country' => 'Vanuatu'],
        ['no' => 152, 'language' => 'French', 'language_id' => 46, 'country' => 'Rwanda'],
        ['no' => 153, 'language' => 'French', 'language_id' => 46, 'country' => 'Chad'],
        ['no' => 154, 'language' => 'French', 'language_id' => 46, 'country' => 'Central African Republic'],
        ['no' => 155, 'language' => 'French', 'language_id' => 46, 'country' => 'Haiti'],
        ['no' => 156, 'language' => 'French', 'language_id' => 46, 'country' => 'Burundi'],
        ['no' => 157, 'language' => 'French', 'language_id' => 46, 'country' => 'Belgium'],
        ['no' => 158, 'language' => 'French', 'language_id' => 46, 'country' => 'Equatorial Guinea'],
        ['no' => 159, 'language' => 'French', 'language_id' => 46, 'country' => 'Canada'],
        ['no' => 160, 'language' => 'French', 'language_id' => 46, 'country' => 'Switzerland'],

        ['no' => 161, 'language' => 'Fula', 'language_id' => 47, 'country' => 'Mali'],
        ['no' => 162, 'language' => 'Gaurasu we', 'language_id' => 48, 'country' => 'Bolivia'],
        ['no' => 163, 'language' => 'Georgian', 'language_id' => 49, 'country' => 'Georgia'],

        ['no' => 164, 'language' => 'German', 'language_id' => 50, 'country' => 'Austria'],
        ['no' => 165, 'language' => 'German', 'language_id' => 50, 'country' => 'Germany'],
        ['no' => 166, 'language' => 'German', 'language_id' => 50, 'country' => 'Liechtenstein'],
        ['no' => 167, 'language' => 'German', 'language_id' => 50, 'country' => 'Switzerland'],
        ['no' => 168, 'language' => 'German', 'language_id' => 50, 'country' => 'Luxembourg'],
        ['no' => 169, 'language' => 'German', 'language_id' => 50, 'country' => 'Belgium'],

        ['no' => 170, 'language' => 'Gilbertese', 'language_id' => 51, 'country' => 'Kiribati'],

        ['no' => 171, 'language' => 'Greek', 'language_id' => 52, 'country' => 'Cyprus'],
        ['no' => 172, 'language' => 'Greek', 'language_id' => 52, 'country' => 'Greece'],

        ['no' => 173, 'language' => 'Guarani', 'language_id' => 53, 'country' => 'Bolivia'],
        ['no' => 174, 'language' => 'Guarani', 'language_id' => 53, 'country' => 'Paraguay'],

        ['no' => 175, 'language' => 'Guarayu', 'language_id' => 54, 'country' => 'Bolivia'],
        ['no' => 176, 'language' => 'Gujarati', 'language_id' => 55, 'country' => 'India'],
        ['no' => 177, 'language' => 'Gurumukhi', 'language_id' => 56, 'country' => 'India'],
        ['no' => 178, 'language' => 'Haitian Creole', 'language_id' => 57, 'country' => 'Haiti'],
        ['no' => 179, 'language' => 'Hassaniya', 'language_id' => 58, 'country' => 'Mali'],
        ['no' => 180, 'language' => 'Hebrew', 'language_id' => 59, 'country' => 'Israel'],

        ['no' => 181, 'language' => 'Hindi', 'language_id' => 60, 'country' => 'India'],
        ['no' => 182, 'language' => 'Hindi', 'language_id' => 60, 'country' => 'Jamaica'],
        ['no' => 183, 'language' => 'Hindi', 'language_id' => 60, 'country' => 'Mauritius'],
        ['no' => 184, 'language' => 'Hindi', 'language_id' => 60, 'country' => 'New Zealand'],
        ['no' => 185, 'language' => 'Hindi', 'language_id' => 60, 'country' => 'Singapore'],
        ['no' => 186, 'language' => 'Hindi', 'language_id' => 60, 'country' => 'Trinidad and Tobago'],
        ['no' => 187, 'language' => 'Hindi', 'language_id' => 60, 'country' => 'United Arab Emirates'],

        ['no' => 188, 'language' => 'Hiri Motu', 'language_id' => 61, 'country' => 'Papua New Guinea'],
        ['no' => 189, 'language' => 'Hungarian', 'language_id' => 62, 'country' => 'Hungary'],
        ['no' => 190, 'language' => 'Icelandic', 'language_id' => 63, 'country' => 'Iceland'],
        ['no' => 191, 'language' => 'Indonesian', 'language_id' => 64, 'country' => 'Indonesia'],
        ['no' => 192, 'language' => 'Irish', 'language_id' => 65, 'country' => 'Ireland'],

        ['no' => 193, 'language' => 'Italian', 'language_id' => 66, 'country' => 'Italy'],
        ['no' => 194, 'language' => 'Italian', 'language_id' => 66, 'country' => 'San Marino'],
        ['no' => 195, 'language' => 'Italian', 'language_id' => 66, 'country' => 'Vatican'],
        ['no' => 196, 'language' => 'Italian', 'language_id' => 66, 'country' => 'Switzerland'],

        ['no' => 197, 'language' => 'Itonama', 'language_id' => 67, 'country' => 'Bolivia'],
        ['no' => 198, 'language' => 'Japanese', 'language_id' => 68, 'country' => 'Japan'],
        ['no' => 199, 'language' => 'Kalanga', 'language_id' => 69, 'country' => 'Zimbabwe'],
        ['no' => 200, 'language' => 'Kannada', 'language_id' => 70, 'country' => 'India'],
        ['no' => 201, 'language' => 'Kassaone', 'language_id' => 71, 'country' => 'Mali'],
        ['no' => 202, 'language' => 'Kazakh', 'language_id' => 72, 'country' => 'Kazakhstan'],
        ['no' => 203, 'language' => 'Khmer', 'language_id' => 73, 'country' => 'Cambodia'],
        ['no' => 204, 'language' => 'Khoisan', 'language_id' => 74, 'country' => 'Zimbabwe'],
        ['no' => 205, 'language' => 'Kinyarwanda', 'language_id' => 75, 'country' => 'Rwanda'],
        ['no' => 206, 'language' => 'Kirundi', 'language_id' => 76, 'country' => 'Burundi'],
        ['no' => 207, 'language' => 'Korean', 'language_id' => 77, 'country' => 'North Korea'],
        ['no' => 208, 'language' => 'Korean', 'language_id' => 77, 'country' => 'South Korea'],
        ['no' => 209, 'language' => 'Kurdish', 'language_id' => 78, 'country' => 'Iraq'],
        ['no' => 210, 'language' => 'Kyrgy', 'language_id' => 79, 'country' => 'Kyrgyzstan'],
        ['no' => 211, 'language' => 'Lao', 'language_id' => 80, 'country' => 'Laos'],
        ['no' => 212, 'language' => 'Latin', 'language_id' => 81, 'country' => 'Vatican'],
        ['no' => 213, 'language' => 'Latvian', 'language_id' => 82, 'country' => 'Latvia'],
        ['no' => 214, 'language' => 'Leco', 'language_id' => 83, 'country' => 'Bolivia'],
        ['no' => 215, 'language' => 'Lithuanian', 'language_id' => 84, 'country' => 'Lithuania'],
        ['no' => 216, 'language' => 'Luxembourgish', 'language_id' => 85, 'country' => 'Luxembourg'],
        ['no' => 217, 'language' => 'Machineri', 'language_id' => 86, 'country' => 'Bolivia'],
        ['no' => 218, 'language' => 'Malagasy', 'language_id' => 87, 'country' => 'Madagascar'],
        ['no' => 219, 'language' => 'Malay', 'language_id' => 88, 'country' => 'Brunei'],
        ['no' => 220, 'language' => 'Malay', 'language_id' => 88, 'country' => 'Malaysia'],
        ['no' => 221, 'language' => 'Malay', 'language_id' => 88, 'country' => 'Singapore'],
        ['no' => 222, 'language' => 'Malayalam', 'language_id' => 89, 'country' => 'India'],
        ['no' => 223, 'language' => 'Maltese', 'language_id' => 90, 'country' => 'Malta'],
        ['no' => 224, 'language' => 'Mandarin Chinese', 'language_id' => 91, 'country' => 'Singapore'],
        ['no' => 225, 'language' => 'Manike', 'language_id' => 92, 'country' => 'Mali'],
        ['no' => 226, 'language' => 'Maori Language', 'language_id' => 93, 'country' => 'New Zealand'],
        ['no' => 227, 'language' => 'Marathi', 'language_id' => 94, 'country' => 'India'],
        ['no' => 228, 'language' => 'Macedonian', 'language_id' => 95, 'country' => 'North Macedonia'],
        ['no' => 229, 'language' => 'Maropa', 'language_id' => 96, 'country' => 'Bolivia'],
        ['no' => 230, 'language' => 'Marshallese', 'language_id' => 97, 'country' => 'Marshall Islands'],
        ['no' => 231, 'language' => 'Mauritian', 'language_id' => 98, 'country' => 'Mauritius'],
        ['no' => 232, 'language' => 'Minyanka', 'language_id' => 99, 'country' => 'Mali'],
        ['no' => 233, 'language' => 'Mojeno -Trinitario', 'language_id' => 100, 'country' => 'Bolivia'],
        ['no' => 234, 'language' => 'Mojeno-Ignaciano', 'language_id' => 101, 'country' => 'Bolivia'],
        ['no' => 235, 'language' => 'Mongolian', 'language_id' => 102, 'country' => 'Mongolia'],
        ['no' => 236, 'language' => 'Montenegrin', 'language_id' => 103, 'country' => 'Montenegro'],
        ['no' => 237, 'language' => 'Moore', 'language_id' => 104, 'country' => 'Bolivia'],
        ['no' => 238, 'language' => 'Moseten', 'language_id' => 105, 'country' => 'Bolivia'],
        ['no' => 239, 'language' => 'Movima', 'language_id' => 106, 'country' => 'Bolivia'],
        ['no' => 240, 'language' => 'Nambya', 'language_id' => 107, 'country' => 'Zimbabwe'],
        ['no' => 241, 'language' => 'Nauruan', 'language_id' => 108, 'country' => 'Nauru'],
        ['no' => 242, 'language' => 'Ndau', 'language_id' => 109, 'country' => 'Zimbabwe'],
        ['no' => 243, 'language' => 'Ndebele', 'language_id' => 110, 'country' => 'South Africa'],
        ['no' => 244, 'language' => 'Ndebele', 'language_id' => 110, 'country' => 'Zimbabwe'],
        ['no' => 245, 'language' => 'Nepali', 'language_id' => 111, 'country' => 'Nepal'],
        ['no' => 246, 'language' => 'Northern Sotho', 'language_id' => 112, 'country' => 'South Africa'],
        ['no' => 247, 'language' => 'Norwegian', 'language_id' => 113, 'country' => 'Norway'],
        ['no' => 248, 'language' => 'Oromo', 'language_id' => 114, 'country' => 'Ethiopia'],
        ['no' => 249, 'language' => 'Odia', 'language_id' => 115, 'country' => 'India'],
        ['no' => 250, 'language' => 'Pacawara', 'language_id' => 116, 'country' => 'Bolivia'],
        ['no' => 251, 'language' => 'Palauan', 'language_id' => 117, 'country' => 'Palau'],
        ['no' => 252, 'language' => 'Pashto', 'language_id' => 118, 'country' => 'Afghanistan'],
        ['no' => 253, 'language' => 'Persian', 'language_id' => 119, 'country' => 'Iran'],
        ['no' => 254, 'language' => 'Persian', 'language_id' => 119, 'country' => 'Afghanistan'],
        ['no' => 255, 'language' => 'Peruvian Spanish', 'language_id' => 120, 'country' => 'Peru'],
        ['no' => 256, 'language' => 'Polish', 'language_id' => 121, 'country' => 'Poland'],

        ['no' => 257, 'language' => 'Portugese', 'language_id' => 122, 'country' => 'Angola'],
        ['no' => 258, 'language' => 'Portugese', 'language_id' => 122, 'country' => 'Brazil'],
        ['no' => 259, 'language' => 'Portugese', 'language_id' => 122, 'country' => 'Cape Verde'],
        ['no' => 260, 'language' => 'Portugese', 'language_id' => 122, 'country' => 'Guinea Bissau'],
        ['no' => 261, 'language' => 'Portugese', 'language_id' => 122, 'country' => 'Mozambique'],
        ['no' => 262, 'language' => 'Portugese', 'language_id' => 122, 'country' => 'Portugal'],
        ['no' => 263, 'language' => 'Portugese', 'language_id' => 122, 'country' => 'Sao Tome and Principe'],
        ['no' => 264, 'language' => 'Portugese', 'language_id' => 122, 'country' => 'Equatorial Guinea'],
        ['no' => 265, 'language' => 'Portugese', 'language_id' => 122, 'country' => 'East Timor'],

        ['no' => 266, 'language' => 'Puquina', 'language_id' => 123, 'country' => 'Bolivia'],
        ['no' => 267, 'language' => 'Quechua', 'language_id' => 124, 'country' => 'Bolivia'],
        ['no' => 268, 'language' => 'Quechua', 'language_id' => 124, 'country' => 'Ecuador'],
        ['no' => 269, 'language' => 'Quechua', 'language_id' => 124, 'country' => 'Peru'],

        ['no' => 270, 'language' => 'Romanian', 'language_id' => 125, 'country' => 'Moldova'],
        ['no' => 271, 'language' => 'Romanian', 'language_id' => 125, 'country' => 'Romania'],
        ['no' => 272, 'language' => 'Romansh', 'language_id' => 126, 'country' => 'Switzerland'],

        ['no' => 273, 'language' => 'Russian', 'language_id' => 127, 'country' => 'Russia'],
        ['no' => 274, 'language' => 'Russian', 'language_id' => 127, 'country' => 'Kyrgyzstan'],
        ['no' => 275, 'language' => 'Russian', 'language_id' => 127, 'country' => 'Belarus'],
        ['no' => 276, 'language' => 'Russian', 'language_id' => 127, 'country' => 'Kazakhstan'],

        ['no' => 277, 'language' => 'Samoan', 'language_id' => 128, 'country' => 'Samoa'],
        ['no' => 278, 'language' => 'Sami languages', 'language_id' => 129, 'country' => 'Norway'],
        ['no' => 279, 'language' => 'Sango', 'language_id' => 130, 'country' => 'Central African Republic'],
        ['no' => 280, 'language' => 'Senufo', 'language_id' => 131, 'country' => 'Azerbaijan'],
        ['no' => 281, 'language' => 'Senufo', 'language_id' => 131, 'country' => 'Mali'],

        ['no' => 282, 'language' => 'Serbian', 'language_id' => 132, 'country' => 'Serbia'],
        ['no' => 283, 'language' => 'Serbian', 'language_id' => 132, 'country' => 'Bosnia and Herzegovina'],
        ['no' => 284, 'language' => 'Seychelles Creole', 'language_id' => 133, 'country' => 'Seychelles'],

        ['no' => 285, 'language' => 'Shangani', 'language_id' => 134, 'country' => 'Zimbabwe'],
        ['no' => 286, 'language' => 'Shona', 'language_id' => 135, 'country' => 'Zimbabwe'],
        ['no' => 287, 'language' => 'Sinhalese', 'language_id' => 136, 'country' => 'Sri Lanka'],
        ['no' => 288, 'language' => 'Siriono', 'language_id' => 137, 'country' => 'Bolivia'],

        ['no' => 289, 'language' => 'Slovak', 'language_id' => 138, 'country' => 'Slovakia'],
        ['no' => 290, 'language' => 'Slovak', 'language_id' => 138, 'country' => 'Czech Republic'],
        ['no' => 291, 'language' => 'Slovene', 'language_id' => 139, 'country' => 'Slovenia'],

        ['no' => 292, 'language' => 'Somali', 'language_id' => 140, 'country' => 'Somalia'],
        ['no' => 293, 'language' => 'Somali', 'language_id' => 140, 'country' => 'Ethiopia'],

        ['no' => 294, 'language' => 'Songhay Languages', 'language_id' => 141, 'country' => 'Mali'],
        ['no' => 295, 'language' => 'Soninke', 'language_id' => 142, 'country' => 'Mali'],

        ['no' => 296, 'language' => 'Sotho', 'language_id' => 143, 'country' => 'Lesotho'],
        ['no' => 297, 'language' => 'Sotho', 'language_id' => 143, 'country' => 'Zimbabwe'],

        ['no' => 298, 'language' => 'Spanish', 'language_id' => 144, 'country' => 'Argentina'],
        ['no' => 299, 'language' => 'Spanish', 'language_id' => 144, 'country' => 'Bolivia'],
        ['no' => 300, 'language' => 'Spanish', 'language_id' => 144, 'country' => 'Chile'],
        ['no' => 301, 'language' => 'Spanish', 'language_id' => 144, 'country' => 'Colombia'],
        ['no' => 302, 'language' => 'Spanish', 'language_id' => 144, 'country' => 'Costa Rica'],
        ['no' => 303, 'language' => 'Spanish', 'language_id' => 144, 'country' => 'Cuba'],
        ['no' => 304, 'language' => 'Spanish', 'language_id' => 144, 'country' => 'Dominican Republic'],
        ['no' => 305, 'language' => 'Spanish', 'language_id' => 144, 'country' => 'Ecuador'],
        ['no' => 306, 'language' => 'Spanish', 'language_id' => 144, 'country' => 'El Salvador'],
        ['no' => 307, 'language' => 'Spanish', 'language_id' => 144, 'country' => 'Equatorial Guinea'],
        ['no' => 308, 'language' => 'Spanish', 'language_id' => 144, 'country' => 'Guatemala'],
        ['no' => 309, 'language' => 'Spanish', 'language_id' => 144, 'country' => 'Honduras'],
        ['no' => 310, 'language' => 'Spanish', 'language_id' => 144, 'country' => 'Mexico'],
        ['no' => 311, 'language' => 'Spanish', 'language_id' => 144, 'country' => 'Nicaragua'],
        ['no' => 312, 'language' => 'Spanish', 'language_id' => 144, 'country' => 'Panama'],
        ['no' => 313, 'language' => 'Spanish', 'language_id' => 144, 'country' => 'Paraguay'],
        ['no' => 314, 'language' => 'Spanish', 'language_id' => 144, 'country' => 'Spain'],
        ['no' => 315, 'language' => 'Spanish', 'language_id' => 144, 'country' => 'Uruguay'],
        ['no' => 316, 'language' => 'Spanish', 'language_id' => 144, 'country' => 'Venezuela'],

        ['no' => 317, 'language' => 'Standard Chinese', 'language_id' => 145, 'country' => 'China'],

        ['no' => 318, 'language' => 'Swahili', 'language_id' => 146, 'country' => 'Kenya'],
        ['no' => 319, 'language' => 'Swahili', 'language_id' => 146, 'country' => 'Tanzania'],
        ['no' => 320, 'language' => 'Swahili', 'language_id' => 146, 'country' => 'Uganda'],
        ['no' => 321, 'language' => 'Swahili', 'language_id' => 146, 'country' => 'Rwanda'],
        ['no' => 322, 'language' => 'Swahili', 'language_id' => 146, 'country' => 'Burundi'],

        ['no' => 323, 'language' => 'Swazi', 'language_id' => 147, 'country' => 'Swaziland'],
        ['no' => 324, 'language' => 'Swazi', 'language_id' => 147, 'country' => 'South Africa'],

        ['no' => 325, 'language' => 'Swedish', 'language_id' => 148, 'country' => 'Sweden'],
        ['no' => 326, 'language' => 'Swedish', 'language_id' => 148, 'country' => 'Finland'],

        ['no' => 327, 'language' => 'Tacana', 'language_id' => 149, 'country' => 'Bolivia'],
        ['no' => 328, 'language' => 'Tajik', 'language_id' => 150, 'country' => 'Tajikistan'],
        ['no' => 329, 'language' => 'Tamasheq', 'language_id' => 151, 'country' => 'Mali'],

        ['no' => 330, 'language' => 'Tamil', 'language_id' => 152, 'country' => 'Singapore'],
        ['no' => 331, 'language' => 'Tamil', 'language_id' => 152, 'country' => 'Sri Lanka'],
        ['no' => 332, 'language' => 'Tamil', 'language_id' => 152, 'country' => 'India'],
        ['no' => 333, 'language' => 'Tamil', 'language_id' => 152, 'country' => 'Malaysia'],
        ['no' => 334, 'language' => 'Tamil', 'language_id' => 152, 'country' => 'Myanmar'],

        ['no' => 335, 'language' => 'Tapiete', 'language_id' => 153, 'country' => 'Bolivia'],
        ['no' => 336, 'language' => 'Telugu', 'language_id' => 154, 'country' => 'India'],
        ['no' => 337, 'language' => 'Tetum', 'language_id' => 155, 'country' => 'East Timor'],
        ['no' => 338, 'language' => 'Thai', 'language_id' => 156, 'country' => 'Thailand'],

        ['no' => 339, 'language' => 'Tigrinya', 'language_id' => 157, 'country' => 'Eritrea'],
        ['no' => 340, 'language' => 'Tigrinya', 'language_id' => 157, 'country' => 'Ethiopia'],

        ['no' => 341, 'language' => 'Tok Pisin', 'language_id' => 158, 'country' => 'Papua New Guinea'],
        ['no' => 342, 'language' => 'Tongan', 'language_id' => 159, 'country' => 'Tonga'],
        ['no' => 343, 'language' => 'Toromona', 'language_id' => 160, 'country' => 'Bolivia'],

        ['no' => 344, 'language' => 'Tsonga', 'language_id' => 161, 'country' => 'South Africa'],
        ['no' => 345, 'language' => 'Tsonga', 'language_id' => 161, 'country' => 'Zimbabwe'],

        ['no' => 346, 'language' => 'Tswana', 'language_id' => 162, 'country' => 'South Africa'],
        ['no' => 347, 'language' => 'Tswana', 'language_id' => 162, 'country' => 'Zimbabwe'],

        ['no' => 348, 'language' => 'Turkish', 'language_id' => 163, 'country' => 'Turkey'],
        ['no' => 349, 'language' => 'Turkish', 'language_id' => 163, 'country' => 'Cyprus'],

        ['no' => 350, 'language' => 'Turkmen', 'language_id' => 164, 'country' => 'Turkmenistan'],
        ['no' => 351, 'language' => 'Tuvaluan', 'language_id' => 165, 'country' => 'Tuvalu'],
        ['no' => 352, 'language' => 'Ukrainian', 'language_id' => 166, 'country' => 'Ukraine'],

        ['no' => 353, 'language' => 'Urdu', 'language_id' => 167, 'country' => 'Pakistan'],
        ['no' => 354, 'language' => 'Urdu', 'language_id' => 167, 'country' => 'India'],
        ['no' => 355, 'language' => 'Urdu', 'language_id' => 167, 'country' => 'Nepal'],
        ['no' => 356, 'language' => 'Urdu', 'language_id' => 167, 'country' => 'Saudi Arabia'],
        ['no' => 357, 'language' => 'Urdu', 'language_id' => 167, 'country' => 'United Arab Emirates'],

        ['no' => 358, 'language' => 'Uru Chipaya', 'language_id' => 168, 'country' => 'Bolivia'],
        ['no' => 359, 'language' => 'Uzbek', 'language_id' => 169, 'country' => 'Uzbekistan'],

        ['no' => 360, 'language' => 'Venda', 'language_id' => 170, 'country' => 'South Africa'],
        ['no' => 361, 'language' => 'Venda', 'language_id' => 170, 'country' => 'Zimbabwe'],

        ['no' => 362, 'language' => 'Vietnamese', 'language_id' => 171, 'country' => 'Vietnam'],
        ['no' => 363, 'language' => 'Weenhayek', 'language_id' => 172, 'country' => 'Bolivia'],

        ['no' => 364, 'language' => 'Xhosa', 'language_id' => 173, 'country' => 'South Africa'],
        ['no' => 365, 'language' => 'Xhosa', 'language_id' => 173, 'country' => 'Zimbabwe'],

        ['no' => 366, 'language' => 'Yaminawa', 'language_id' => 174, 'country' => 'Bolivia'],
        ['no' => 367, 'language' => 'Yuki', 'language_id' => 175, 'country' => 'Bolivia'],
        ['no' => 368, 'language' => 'Yuracare', 'language_id' => 176, 'country' => 'Bolivia'],
        ['no' => 369, 'language' => 'Zamuco', 'language_id' => 177, 'country' => 'Bolivia'],
        ['no' => 370, 'language' => 'Zulu', 'language_id' => 178, 'country' => 'South Africa'],

    ],
];
