<?php

$regionsData = [
    [
        'region' => 'Africa',
        'population_million' => 1548,
        'literacy_percent' => 67,
        'internet_access_percent' => 38,
        'social_media' => [
            'facebook_percent' => 7,
            'instagram_percent' => 6,
            'linkedin_percent' => 6,
            'twitter_percent' => 1,
        ],
        'countries' => 54,
    ],
    [
        'region' => 'Asia',
        'population_million' => 4247,
        'literacy_percent' => 85,
        'internet_access_percent' => 68,
        'social_media' => [
            'facebook_percent' => 9,
            'instagram_percent' => 18,
            'linkedin_percent' => 7,
            'twitter_percent' => 3,
        ],
        'countries' => 37,
    ],
    [
        'region' => 'Central America and the Caribbean',
        'population_million' => 225,
        'literacy_percent' => 91,
        'internet_access_percent' => 73,
        'social_media' => [
            'facebook_percent' => 39,
            'instagram_percent' => 34,
            'linkedin_percent' => 20,
            'twitter_percent' => 7,
        ],
        'countries' => 21,
    ],
    [
        'region' => 'Europe',
        'population_million' => 600,
        'literacy_percent' => 99,
        'internet_access_percent' => 90,
        'social_media' => [
            'facebook_percent' => 36,
            'instagram_percent' => 44,
            'linkedin_percent' => 44,
            'twitter_percent' => 11,
        ],
        'countries' => 44,
    ],
    [
        'region' => 'North America',
        'population_million' => 387,
        'literacy_percent' => 87,
        'internet_access_percent' => 96,
        'social_media' => [
            'facebook_percent' => 45,
            'instagram_percent' => 51,
            'linkedin_percent' => 77,
            'twitter_percent' => 20,
        ],
        'countries' => 2,
    ],
    [
        'region' => 'South America',
        'population_million' => 438,
        'literacy_percent' => 95,
        'internet_access_percent' => 80,
        'social_media' => [
            'facebook_percent' => 37,
            'instagram_percent' => 57,
            'linkedin_percent' => 39,
            'twitter_percent' => 6,
        ],
        'countries' => 12,
    ],
    [
        'region' => 'South East Asia and Oceania',
        'population_million' => 746,
        'literacy_percent' => 94,
        'internet_access_percent' => 72,
        'social_media' => [
            'facebook_percent' => 32,
            'instagram_percent' => 43,
            'linkedin_percent' => 16,
            'twitter_percent' => 6,
        ],
        'countries' => 25,
    ],
    [
        'region' => 'Total',
        'population_million' => 8191,
        'literacy_percent' => 84,
        'internet_access_percent' => 67,
        'social_media' => [
            'facebook_percent' => 16,
            'instagram_percent' => 24,
            'linkedin_percent' => 16,
            'twitter_percent' => 4,
        ],
        'countries' => 195,
    ],
];
