<?php

return [



    'digital_divide_languages' => [
        ['language_id' => 145, 'no' => 1, 'language' => 'Standard Chinese', 'spoken_family' => 'Sino-Tibetan', 'population_2021' => '21.01%', 'internet_content' => '1.10%', 'wikipedia_content' => '2.29%', 'script' => 'Hanzi', 'writing_family' => 'Hanzi Script', 'writing_system' => 'Logo Syllabic', 'countries_count' => 1],
        ['language_id' => 60, 'no' => 2, 'language' => 'Hindi', 'spoken_family' => 'Indoeuropean', 'population_2021' => '9.53%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '0.25%', 'script' => 'Devanagari', 'writing_family' => 'North Indic Scripts', 'writing_system' => 'Varnamala/Abugida', 'countries_count' => 7],
        ['language_id' => 144, 'no' => 3, 'language' => 'Spanish', 'spoken_family' => 'Indoeuropean', 'population_2021' => '7.23%', 'internet_content' => '6.00%', 'wikipedia_content' => '3.14%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 19],
        ['language_id' => 3, 'no' => 4, 'language' => 'Arabic', 'spoken_family' => 'Afroasiatic', 'population_2021' => '5.86%', 'internet_content' => '0.60%', 'wikipedia_content' => '1.95%', 'script' => 'Arabic', 'writing_family' => 'Arabic Script', 'writing_system' => 'Abjad', 'countries_count' => 23],
        ['language_id' => 167, 'no' => 5, 'language' => 'Urdu', 'spoken_family' => 'Indoeuropean', 'population_2021' => '3.18%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '0.36%', 'script' => 'Perso-Arabic', 'writing_family' => 'Arabic Script', 'writing_system' => 'Abjad', 'countries_count' => 5],
        ['language_id' => 13, 'no' => 6, 'language' => 'Bengali', 'spoken_family' => 'Indoeuropean', 'population_2021' => '2.34%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '0.27%', 'script' => 'Bengali', 'writing_family' => 'North Indic Scripts', 'writing_system' => 'Varnamala/Abugida', 'countries_count' => 4],
        ['language_id' => 152, 'no' => 7, 'language' => 'Tamil', 'spoken_family' => 'Afroasiatic', 'population_2021' => '1.48%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '0.27%', 'script' => 'Tamil', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 5],
        ['language_id' => 94, 'no' => 8, 'language' => 'Marathi', 'spoken_family' => 'Indoeuropean', 'population_2021' => '1.42%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '0.15%', 'script' => 'Devanagari', 'writing_family' => 'North Indic Scripts', 'writing_system' => 'Varnamala/Abugida', 'countries_count' => 1],
        ['language_id' => 154, 'no' => 9, 'language' => 'Telugu', 'spoken_family' => 'Indoeuropean', 'population_2021' => '1.41%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '0.18%', 'script' => 'Telugu', 'writing_family' => 'South Indic Script', 'writing_system' => 'Varnamala/Abugida', 'countries_count' => 1],
        ['language_id' => 119, 'no' => 10, 'language' => 'Persian', 'spoken_family' => 'Indoeuropean', 'population_2021' => '1.40%', 'internet_content' => '0.90%', 'wikipedia_content' => '1.60%', 'script' => 'Perso-Arabic', 'writing_family' => 'Arabic Script', 'writing_system' => 'Abjad', 'countries_count' => 2],
        ['language_id' => 77, 'no' => 11, 'language' => 'Korean', 'spoken_family' => 'Others', 'population_2021' => '1.27%', 'internet_content' => '0.80%', 'wikipedia_content' => '1.11%', 'script' => 'Hangul', 'writing_family' => 'Hangul Script', 'writing_system' => 'Alphabetical', 'countries_count' => 2],
        ['language_id' => 55, 'no' => 12, 'language' => 'Gujarati', 'spoken_family' => 'Indoeuropean', 'population_2021' => '0.87%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Gujarati', 'writing_family' => 'North Indic Scripts', 'writing_system' => 'Varnamala/Abugida', 'countries_count' => 1],
        ['language_id' => 44, 'no' => 13, 'language' => 'Filipino', 'spoken_family' => 'Austronesian', 'population_2021' => '0.81%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 70, 'no' => 14, 'language' => 'Kannada', 'spoken_family' => 'Dravidian', 'population_2021' => '0.75%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Kannada', 'writing_family' => 'South Indic Script', 'writing_system' => 'Varnamala/Abugida', 'countries_count' => 1],
        ['language_id' => 118, 'no' => 15, 'language' => 'Pashto', 'spoken_family' => 'Indoeuropean', 'population_2021' => '0.74%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Arabic', 'writing_family' => 'Arabic Script', 'writing_system' => 'Abjad', 'countries_count' => 1],
        ['language_id' => 56, 'no' => 16, 'language' => 'Gurmukhi', 'spoken_family' => 'Indoeuropean', 'population_2021' => '0.69%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Gurmukhi', 'writing_family' => 'North Indic Scripts', 'writing_system' => 'Varnamala/Abugida', 'countries_count' => 1],
        ['language_id' => 156, 'no' => 17, 'language' => 'Thai', 'spoken_family' => 'Tai-Kadai', 'population_2021' => '0.64%', 'internet_content' => '0.30%', 'wikipedia_content' => '0.27%', 'script' => 'Thai', 'writing_family' => 'South Indic Script', 'writing_system' => 'Varnamala/Abugida', 'countries_count' => 1],
        ['language_id' => 21, 'no' => 18, 'language' => 'Burmese', 'spoken_family' => 'Sino-Tibetan', 'population_2021' => '0.62%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '0.17%', 'script' => 'Mon', 'writing_family' => 'South Indic Script', 'writing_system' => 'Varnamala/Abugida', 'countries_count' => 1],
        ['language_id' => 89, 'no' => 19, 'language' => 'Malayalam', 'spoken_family' => 'Dravidian', 'population_2021' => '0.61%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '0.13%', 'script' => 'Malayalam', 'writing_family' => 'South Indic Script', 'writing_system' => 'Varnamala/Abugida', 'countries_count' => 1],
        ['language_id' => 88, 'no' => 20, 'language' => 'Malay', 'spoken_family' => 'Austronesian', 'population_2021' => '0.57%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '0.66%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 3],
        ['language_id' => 146, 'no' => 21, 'language' => 'Swahili', 'spoken_family' => 'Niger-Congo', 'population_2021' => '0.53%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '0.16%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 5],
        ['language_id' => 9, 'no' => 22, 'language' => 'Azerbaijani', 'spoken_family' => 'Turkic', 'population_2021' => '0.53%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '0.32%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 169, 'no' => 23, 'language' => 'Uzbek', 'spoken_family' => 'Turkic', 'population_2021' => '0.49%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '0.50%', 'script' => 'Cyrillic', 'writing_family' => 'Cyrillic Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 78, 'no' => 24, 'language' => 'Kurdish', 'spoken_family' => 'Indoeuropean', 'population_2021' => '0.47%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '0.14%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 140, 'no' => 25, 'language' => 'Somali', 'spoken_family' => 'Afroasiatic', 'population_2021' => '0.41%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 2],
        ['language_id' => 75, 'no' => 26, 'language' => 'Kinyarwanda', 'spoken_family' => 'Niger-Congo', 'population_2021' => '0.41%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 63, 'no' => 27, 'language' => 'Icelandic', 'spoken_family' => 'Indoeuropean', 'population_2021' => '0.40%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 91, 'no' => 28, 'language' => 'Mandarin Chinese', 'spoken_family' => 'Sino-Tibetan', 'population_2021' => '0.38%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Hanzi', 'writing_family' => 'Hanzi Script', 'writing_system' => 'Logo Syllabic', 'countries_count' => 1],
        ['language_id' => 80, 'no' => 29, 'language' => 'Lao', 'spoken_family' => 'Tai-Kadai', 'population_2021' => '0.35%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Lao', 'writing_family' => 'South Indic Script', 'writing_system' => 'Varnamala/Abugida', 'countries_count' => 1],
        ['language_id' => 47, 'no' => 30, 'language' => 'Fula', 'spoken_family' => 'Niger-Congo', 'population_2021' => '0.34%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 73, 'no' => 31, 'language' => 'Khmer', 'spoken_family' => 'Austroasiatic', 'population_2021' => '0.31%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Khmer', 'writing_family' => 'South Indic Script', 'writing_system' => 'Varnamala/Abugida', 'countries_count' => 1],
        ['language_id' => 27, 'no' => 32, 'language' => 'Chichewa', 'spoken_family' => 'Niger-Congo', 'population_2021' => '0.31%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 14, 'no' => 33, 'language' => 'Berber', 'spoken_family' => 'Afroasiatic', 'population_2021' => '0.29%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Tifinagh', 'writing_family' => 'Tifinagh Script', 'writing_system' => 'Abjad', 'countries_count' => 2],
        ['language_id' => 76, 'no' => 34, 'language' => 'Kirundi', 'spoken_family' => 'Niger-Congo', 'population_2021' => '0.28%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 111, 'no' => 35, 'language' => 'Nepali', 'spoken_family' => 'Indoeuropean', 'population_2021' => '0.25%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Devanagari', 'writing_family' => 'North Indic Scripts', 'writing_system' => 'Varnamala/Abugida', 'countries_count' => 1],
        ['language_id' => 72, 'no' => 36, 'language' => 'Kazakh', 'spoken_family' => 'Turkic', 'population_2021' => '0.25%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '0.36%', 'script' => 'Cyrillic', 'writing_family' => 'Cyrillic Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 7, 'no' => 37, 'language' => 'Assamese', 'spoken_family' => 'Indoeuropean', 'population_2021' => '0.24%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Assamese', 'writing_family' => 'North Indic Scripts', 'writing_system' => 'Varnamala/Abugida', 'countries_count' => 1],
        ['language_id' => 136, 'no' => 38, 'language' => 'Sinhalese', 'spoken_family' => 'Indoeuropean', 'population_2021' => '0.23%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Sinhala', 'writing_family' => 'South Indic Script', 'writing_system' => 'Varnamala/Abugida', 'countries_count' => 1],
        ['language_id' => 143, 'no' => 39, 'language' => 'Sotho', 'spoken_family' => 'Niger-Congo', 'population_2021' => '0.22%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 2],
        ['language_id' => 178, 'no' => 40, 'language' => 'Zulu', 'spoken_family' => 'Niger-Congo', 'population_2021' => '0.20%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 10, 'no' => 41, 'language' => 'Bambara', 'spoken_family' => 'Indoeuropean', 'population_2021' => '0.20%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 92, 'no' => 42, 'language' => 'Manike', 'spoken_family' => 'Niger-Congo', 'population_2021' => '0.17%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 157, 'no' => 43, 'language' => 'Tigrinya', 'spoken_family' => 'Afroasiatic', 'population_2021' => '0.17%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => "Ge'ez", 'writing_family' => 'Ethiopic Script', 'writing_system' => 'Varnamala/Abugida', 'countries_count' => 2],
        ['language_id' => 57, 'no' => 44, 'language' => 'Haitian Creole', 'spoken_family' => 'Indoeuropean', 'population_2021' => '0.16%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '0.11%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 23, 'no' => 45, 'language' => 'Catalan', 'spoken_family' => 'Indoeuropean', 'population_2021' => '0.15%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 124, 'no' => 46, 'language' => 'Quechua', 'spoken_family' => 'Others', 'population_2021' => '0.14%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 3],
        ['language_id' => 135, 'no' => 47, 'language' => 'Shona', 'spoken_family' => 'Niger-Congo', 'population_2021' => '0.14%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 102, 'no' => 48, 'language' => 'Mongolian', 'spoken_family' => 'Others', 'population_2021' => '0.14%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Mongolian', 'writing_family' => 'Mongolian Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 141, 'no' => 49, 'language' => 'Songhay Languages', 'spoken_family' => 'Nilo-Saharan', 'population_2021' => '0.12%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 150, 'no' => 50, 'language' => 'Tajik', 'spoken_family' => 'Indoeuropean', 'population_2021' => '0.12%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '0.18%', 'script' => 'Cyrillic', 'writing_family' => 'Cyrillic Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 164, 'no' => 51, 'language' => 'Turkmen', 'spoken_family' => 'Turkic', 'population_2021' => '0.11%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 162, 'no' => 52, 'language' => 'Tswana', 'spoken_family' => 'Niger-Congo', 'population_2021' => '0.11%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 2],
        ['language_id' => 1, 'no' => 53, 'language' => 'Afrikaans', 'spoken_family' => 'Indoeuropean', 'population_2021' => '0.11%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '0.19%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 53, 'no' => 54, 'language' => 'Guarani', 'spoken_family' => 'Tupian', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 2],
        ['language_id' => 5, 'no' => 55, 'language' => 'Armenian', 'spoken_family' => 'Indoeuropean', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '0.49%', 'script' => 'Armenian', 'writing_family' => 'Armenian Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 112, 'no' => 56, 'language' => 'Northern Sotho', 'spoken_family' => 'Niger-Congo', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 114, 'no' => 57, 'language' => 'Oromo', 'spoken_family' => 'Afroasiatic', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 79, 'no' => 58, 'language' => 'Kyrgy', 'spoken_family' => 'Turkic', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Cyrillic', 'writing_family' => 'Cyrillic Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 2, 'no' => 59, 'language' => 'Albanian', 'spoken_family' => 'Indoeuropean', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '0.16%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 2],
        ['language_id' => 134, 'no' => 60, 'language' => 'Shangani', 'spoken_family' => 'Niger-Congo', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 12, 'no' => 61, 'language' => 'Belurusian', 'spoken_family' => 'Indoeuropean', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '0.39%', 'script' => 'Cyrillic', 'writing_family' => 'Cyrillic Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 161, 'no' => 62, 'language' => 'Tsonga', 'spoken_family' => 'Niger-Congo', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 2],
        ['language_id' => 110, 'no' => 63, 'language' => 'Ndebele', 'spoken_family' => 'Niger-Congo', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 49, 'no' => 64, 'language' => 'Georgian', 'spoken_family' => 'Others', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '0.29%', 'script' => 'Georgian', 'writing_family' => 'Georgian Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 28, 'no' => 65, 'language' => 'Chibarwe', 'spoken_family' => 'Niger-Congo', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Ethiopic Script', 'writing_system' => 'Varnamala/Abugida', 'countries_count' => 1],
        ['language_id' => 170, 'no' => 66, 'language' => 'Venda', 'spoken_family' => 'Niger-Congo', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 2],
        ['language_id' => 87, 'no' => 67, 'language' => 'Malagasy', 'spoken_family' => 'Austronesian', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '0.15%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 8, 'no' => 68, 'language' => 'Aymara', 'spoken_family' => 'Others', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 2],
        ['language_id' => 147, 'no' => 69, 'language' => 'Swazi', 'spoken_family' => 'Niger-Congo', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 2],
        ['language_id' => 173, 'no' => 70, 'language' => 'Xhosa', 'spoken_family' => 'Niger-Congo', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 2],
        ['language_id' => 142, 'no' => 71, 'language' => 'Soninke', 'spoken_family' => 'Niger-Congo', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 120, 'no' => 72, 'language' => 'Peruvian Spanish', 'spoken_family' => 'Indoeuropean', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 65, 'no' => 73, 'language' => 'Irish', 'spoken_family' => 'Indoeuropean', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 29, 'no' => 74, 'language' => 'Chilian', 'spoken_family' => 'Indoeuropean', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 95, 'no' => 75, 'language' => 'Macedonian', 'spoken_family' => 'Indoeuropean', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '0.24%', 'script' => 'Cyrillic', 'writing_family' => 'Cyrillic Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 18, 'no' => 76, 'language' => 'Bosnian', 'spoken_family' => 'Indoeuropean', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '0.15%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 31, 'no' => 77, 'language' => 'Comorian', 'spoken_family' => 'Niger-Congo', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Arabic', 'writing_family' => 'Arabic Script', 'writing_system' => 'Abjad', 'countries_count' => 1],
        ['language_id' => 98, 'no' => 78, 'language' => 'Mauritian', 'spoken_family' => 'Indoeuropean', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 71, 'no' => 79, 'language' => 'Kassaone', 'spoken_family' => 'Niger-Congo', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Cyrillic', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 69, 'no' => 80, 'language' => 'Kalanga', 'spoken_family' => 'Niger-Congo', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '0.11%', 'script' => 'Kirat-Sirijonga', 'writing_family' => 'Ethiopic Script', 'writing_system' => 'Varnamala/Abugida', 'countries_count' => 1],
        ['language_id' => 99, 'no' => 81, 'language' => 'Minyanka', 'spoken_family' => 'Niger-Congo', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Arabic', 'writing_family' => 'Arabic Script', 'writing_system' => 'Abjad', 'countries_count' => 1],
        ['language_id' => 17, 'no' => 82, 'language' => 'Bobo', 'spoken_family' => 'Niger-Congo', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Arabic Script', 'writing_system' => 'Abjad', 'countries_count' => 1],
        ['language_id' => 153, 'no' => 83, 'language' => 'Tapiete', 'spoken_family' => 'Tupian', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 155, 'no' => 84, 'language' => 'Tetum', 'spoken_family' => 'Austronesian', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 90, 'no' => 85, 'language' => 'Maltese', 'spoken_family' => 'Afroasiatic', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 35, 'no' => 86, 'language' => 'Dhivehi', 'spoken_family' => 'Indoeuropean', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Thaana', 'writing_family' => 'Thaana Script', 'writing_system' => 'Varnamala/Abugida', 'countries_count' => 1],
        ['language_id' => 42, 'no' => 87, 'language' => 'Fiji Hindi', 'spoken_family' => 'Indoeuropean', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Devanagari', 'writing_family' => 'North Indic Scripts', 'writing_system' => 'Varnamala/Abugida', 'countries_count' => 1],
        ['language_id' => 130, 'no' => 88, 'language' => 'Sango', 'spoken_family' => 'Indoeuropean', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 115, 'no' => 89, 'language' => 'Odia', 'spoken_family' => 'Indoeuropean', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Odia', 'writing_family' => 'North Indic Scripts', 'writing_system' => 'Varnamala/Abugida', 'countries_count' => 1],
        ['language_id' => 43, 'no' => 90, 'language' => 'Fijian', 'spoken_family' => 'Austronesian', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 85, 'no' => 91, 'language' => 'Luxembourgish', 'spoken_family' => 'Indoeuropean', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 151, 'no' => 92, 'language' => 'Tamasheq', 'spoken_family' => 'Afroasiatic', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 103, 'no' => 93, 'language' => 'Montenegrin', 'spoken_family' => 'Indoeuropean', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Cyrillic', 'writing_family' => 'Cyrillic Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 128, 'no' => 94, 'language' => 'Samoan', 'spoken_family' => 'Austronesian', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 93, 'no' => 95, 'language' => 'Maori Language', 'spoken_family' => 'Austronesian', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 38, 'no' => 96, 'language' => 'Dzongkha', 'spoken_family' => 'Sino-Tibetan', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Uchen', 'writing_family' => 'North Indic Scripts', 'writing_system' => 'Varnamala/Abugida', 'countries_count' => 1],
        ['language_id' => 159, 'no' => 97, 'language' => 'Tongan', 'spoken_family' => 'Austronesian', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 131, 'no' => 98, 'language' => 'Senufo', 'spoken_family' => 'Niger-Congo', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 2],
        ['language_id' => 158, 'no' => 99, 'language' => 'Tok Pisin', 'spoken_family' => 'Indoeuropean', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 107, 'no' => 100, 'language' => 'Nambya', 'spoken_family' => 'Niger-Congo', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 58, 'no' => 101, 'language' => 'Hassaniya', 'spoken_family' => 'Afroasiatic', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Arabic', 'writing_family' => 'Arabic Script', 'writing_system' => 'Abjad', 'countries_count' => 1],
        ['language_id' => 51, 'no' => 102, 'language' => 'Gilbertese', 'spoken_family' => 'Austronesian', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 19, 'no' => 103, 'language' => 'Bozo', 'spoken_family' => 'Niger-Congo', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Arabic', 'writing_family' => 'Arabic Script', 'writing_system' => 'Abjad', 'countries_count' => 1],
        ['language_id' => 61, 'no' => 104, 'language' => 'Hiri Motu', 'spoken_family' => 'Austronesian', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 133, 'no' => 105, 'language' => 'Seychelles Creole', 'spoken_family' => 'Indoeuropean', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 74, 'no' => 106, 'language' => 'Khoisan', 'spoken_family' => 'Others', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 36, 'no' => 107, 'language' => 'Dogon', 'spoken_family' => 'Niger-Congo', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Arabic', 'writing_family' => 'Arabic Script', 'writing_system' => 'Abjad', 'countries_count' => 1],
        ['language_id' => 126, 'no' => 108, 'language' => 'Romansh', 'spoken_family' => 'Indoeuropean', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 97, 'no' => 109, 'language' => 'Marshallese', 'spoken_family' => 'Austronesian', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 129, 'no' => 110, 'language' => 'Sami languages', 'spoken_family' => 'Uralic', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Cyrillic Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 54, 'no' => 111, 'language' => 'Guarayu', 'spoken_family' => 'Tupian', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 6, 'no' => 112, 'language' => 'Ashaninka', 'spoken_family' => 'Others', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 117, 'no' => 113, 'language' => 'Palauan', 'spoken_family' => 'Austronesian', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 16, 'no' => 114, 'language' => 'Bislama', 'spoken_family' => 'Indoeuropean', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 165, 'no' => 115, 'language' => 'Tuvaluan', 'spoken_family' => 'Austronesian', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 100, 'no' => 116, 'language' => 'Mojeno-Trinitario', 'spoken_family' => 'Others', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 108, 'no' => 117, 'language' => 'Nauruan', 'spoken_family' => 'Austronesian', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 101, 'no' => 118, 'language' => 'Mojeno-Ignaciano', 'spoken_family' => 'Others', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 30, 'no' => 119, 'language' => 'Chiman', 'spoken_family' => 'Others', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 86, 'no' => 120, 'language' => 'Machineri', 'spoken_family' => 'Others', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 177, 'no' => 121, 'language' => 'Zamuco', 'spoken_family' => 'Others', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 176, 'no' => 122, 'language' => 'Yuracare', 'spoken_family' => 'Others', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 174, 'no' => 123, 'language' => 'Yaminawa', 'spoken_family' => 'Others', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 15, 'no' => 124, 'language' => 'Besiro (Chiquitano)', 'spoken_family' => 'Indoeuropean', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 172, 'no' => 125, 'language' => 'Weenhayek', 'spoken_family' => 'Others', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 168, 'no' => 126, 'language' => 'Uru Chipaya', 'spoken_family' => 'Others', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 149, 'no' => 127, 'language' => 'Tacana', 'spoken_family' => 'Others', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 26, 'no' => 128, 'language' => 'Chacobo', 'spoken_family' => 'Others', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 106, 'no' => 129, 'language' => 'Movima', 'spoken_family' => 'Others', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 22, 'no' => 130, 'language' => 'Canichana', 'spoken_family' => 'Others', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 105, 'no' => 131, 'language' => 'Moseten', 'spoken_family' => 'Others', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Hebrew Script', 'writing_system' => 'Abjad', 'countries_count' => 1],
        ['language_id' => 40, 'no' => 132, 'language' => 'Ese Ejja', 'spoken_family' => 'Others', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 4, 'no' => 133, 'language' => 'Araona', 'spoken_family' => 'Others', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 25, 'no' => 134, 'language' => 'Cayubaba', 'spoken_family' => 'Others', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 24, 'no' => 135, 'language' => 'Cavinena', 'spoken_family' => 'Others', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 137, 'no' => 136, 'language' => 'Siriono', 'spoken_family' => 'Tupian', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 81, 'no' => 137, 'language' => 'Latin', 'spoken_family' => 'Indoeuropean', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '0.21%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 96, 'no' => 138, 'language' => 'Maropa', 'spoken_family' => 'Others', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 160, 'no' => 139, 'language' => 'Toromona', 'spoken_family' => 'Others', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 48, 'no' => 140, 'language' => 'Gaurasu we', 'spoken_family' => 'Tupian', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 175, 'no' => 141, 'language' => 'Yuki', 'spoken_family' => 'Tupian', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 116, 'no' => 142, 'language' => 'Pacawara', 'spoken_family' => 'Others', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 104, 'no' => 143, 'language' => 'Moore', 'spoken_family' => 'Niger-Congo', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 83, 'no' => 144, 'language' => 'Leco', 'spoken_family' => 'Indoeuropean', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 11, 'no' => 145, 'language' => 'Baure', 'spoken_family' => 'Others', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 67, 'no' => 146, 'language' => 'Itonama', 'spoken_family' => 'Others', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 109, 'no' => 147, 'language' => 'Ndau', 'spoken_family' => 'Niger-Congo', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],
        ['language_id' => 123, 'no' => 148, 'language' => 'Puquina', 'spoken_family' => 'Others', 'population_2021' => '< 0.10%', 'internet_content' => '< 0.10%', 'wikipedia_content' => '< 0.10%', 'script' => 'Latin', 'writing_family' => 'Latin Script', 'writing_system' => 'Alphabetical', 'countries_count' => 1],

    ],



    'digitally_balanced_languages' => [

        [
            'language_id' => 39,
            'rank' => 1,
            'language' => 'English',
            'family_spoken' => 'Indoeuropean',
            'population_2021' => '10.19%',
            'internet_content' => '49.60%',
            'wikipedia_content' => '10.72%',
            'script' => 'Latin',
            'writing_family' => 'Latin Script',
            'writing_system' => 'Alphabetical',
            'countries' => 58,
        ],
        [
            'language_id' => 122,
            'rank' => 2,
            'language' => 'Portugese',
            'family_spoken' => 'Indoeuropean',
            'population_2021' => '3.79%',
            'internet_content' => '4.00%',
            'wikipedia_content' => '1.75%',
            'script' => 'Latin',
            'writing_family' => 'Latin Script',
            'writing_system' => 'Alphabetical',
            'countries' => 9,
        ],
        [
            'language_id' => 127,
            'rank' => 3,
            'language' => 'Russian',
            'family_spoken' => 'Indoeuropean',
            'population_2021' => '2.41%',
            'internet_content' => '3.60%',
            'wikipedia_content' => '3.13%',
            'script' => 'Cyrillic',
            'writing_family' => 'Cyrillic Script',
            'writing_system' => 'Alphabetical',
            'countries' => 4,
        ],
        [
            'language_id' => 68,
            'rank' => 4,
            'language' => 'Japanese',
            'family_spoken' => 'Others',
            'population_2021' => '1.92%',
            'internet_content' => '5.10%',
            'wikipedia_content' => '2.24%',
            'script' => 'Hiragana/Katakana',
            'writing_family' => 'Kana/Kanji',
            'writing_system' => 'Logo Syllabic',
            'countries' => 1,
        ],
        [
            'language_id' => 46,
            'rank' => 5,
            'language' => 'French',
            'family_spoken' => 'Indoeuropean',
            'population_2021' => '1.64%',
            'internet_content' => '4.50%',
            'wikipedia_content' => '4.11%',
            'script' => 'Latin',
            'writing_family' => 'Latin Script',
            'writing_system' => 'Alphabetical',
            'countries' => 28,
        ],
        [
            'language_id' => 50,
            'rank' => 6,
            'language' => 'German',
            'family_spoken' => 'Indoeuropean',
            'population_2021' => '1.54%',
            'internet_content' => '6.00%',
            'wikipedia_content' => '4.65%',
            'script' => 'Latin',
            'writing_family' => 'Latin Script',
            'writing_system' => 'Alphabetical',
            'countries' => 6,
        ],
        [
            'language_id' => 163,
            'rank' => 7,
            'language' => 'Turkish',
            'family_spoken' => 'Turkic',
            'population_2021' => '1.35%',
            'internet_content' => '1.60%',
            'wikipedia_content' => '1.00%',
            'script' => 'Latin',
            'writing_family' => 'Latin Script',
            'writing_system' => 'Alphabetical',
            'countries' => 2,
        ],
        [
            'language_id' => 66,
            'rank' => 8,
            'language' => 'Italian',
            'family_spoken' => 'Indoeuropean',
            'population_2021' => '0.95%',
            'internet_content' => '2.80%',
            'wikipedia_content' => '2.94%',
            'script' => 'Latin',
            'writing_family' => 'Latin Script',
            'writing_system' => 'Alphabetical',
            'countries' => 4,
        ],
        [
            'language_id' => 121,
            'rank' => 9,
            'language' => 'Polish',
            'family_spoken' => 'Indoeuropean',
            'population_2021' => '0.59%',
            'internet_content' => '1.80%',
            'wikipedia_content' => '2.53%',
            'script' => 'Latin',
            'writing_family' => 'Latin Script',
            'writing_system' => 'Alphabetical',
            'countries' => 1,
        ],
        [
            'language_id' => 166,
            'rank' => 10,
            'language' => 'Ukrainian',
            'family_spoken' => 'Indoeuropean',
            'population_2021' => '0.43%',
            'internet_content' => '0.70%',
            'wikipedia_content' => '2.11%',
            'script' => 'Cyrillic',
            'writing_family' => 'Cyrillic Script',
            'writing_system' => 'Alphabetical',
            'countries' => 1,
        ],
        [
            'language_id' => 64,
            'rank' => 11,
            'language' => 'Indonesian',
            'family_spoken' => 'Austronesian',
            'population_2021' => '0.39%',
            'internet_content' => '0.90%',
            'wikipedia_content' => '1.15%',
            'script' => 'Latin',
            'writing_family' => 'Latin Script',
            'writing_system' => 'Alphabetical',
            'countries' => 1,
        ],
        [
            'language_id' => 37,
            'rank' => 12,
            'language' => 'Dutch',
            'family_spoken' => 'Indoeuropean',
            'population_2021' => '0.30%',
            'internet_content' => '2.20%',
            'wikipedia_content' => '3.32%',
            'script' => 'Latin',
            'writing_family' => 'Latin Script',
            'writing_system' => 'Alphabetical',
            'countries' => 3,
        ],
        [
            'language_id' => 125,
            'rank' => 13,
            'language' => 'Romanian',
            'family_spoken' => 'Indoeuropean',
            'population_2021' => '0.28%',
            'internet_content' => '0.50%',
            'wikipedia_content' => '0.81%',
            'script' => 'Latin',
            'writing_family' => 'Latin Script',
            'writing_system' => 'Alphabetical',
            'countries' => 2,
        ],
        [
            'language_id' => 52,
            'rank' => 14,
            'language' => 'Greek',
            'family_spoken' => 'Indoeuropean',
            'population_2021' => '0.18%',
            'internet_content' => '0.50%',
            'wikipedia_content' => '0.40%',
            'script' => 'Greek',
            'writing_family' => 'Greek Script',
            'writing_system' => 'Alphabetical',
            'countries' => 2,
        ],
        [
            'language_id' => 62,
            'rank' => 15,
            'language' => 'Hungarian',
            'family_spoken' => 'Indoeuropean',
            'population_2021' => '0.16%',
            'internet_content' => '0.60%',
            'wikipedia_content' => '0.85%',
            'script' => 'Latin',
            'writing_family' => 'Latin Script',
            'writing_system' => 'Alphabetical',
            'countries' => 1,
        ],
        [
            'language_id' => 148,
            'rank' => 16,
            'language' => 'Swedish',
            'family_spoken' => 'Indoeuropean',
            'population_2021' => '0.16%',
            'internet_content' => '0.50%',
            'wikipedia_content' => '3.94%',
            'script' => 'Latin',
            'writing_family' => 'Latin Script',
            'writing_system' => 'Alphabetical',
            'countries' => 2,
        ],
        [
            'language_id' => 33,
            'rank' => 17,
            'language' => 'Czech',
            'family_spoken' => 'Indoeuropean',
            'population_2021' => '0.15%',
            'internet_content' => '1.00%',
            'wikipedia_content' => '0.88%',
            'script' => 'Latin',
            'writing_family' => 'Latin Script',
            'writing_system' => 'Alphabetical',
            'countries' => 1,
        ],
        [
            'language_id' => 171,
            'rank' => 18,
            'language' => 'Vietnamese',
            'family_spoken' => 'Austronesian',
            'population_2021' => '0.14%',
            'internet_content' => '1.00%',
            'wikipedia_content' => '1.95%',
            'script' => 'Latin',
            'writing_family' => 'Latin Script',
            'writing_system' => 'Alphabetical',
            'countries' => 1,
        ],
        [
            'language_id' => 59,
            'rank' => 19,
            'language' => 'Hebrew',
            'family_spoken' => 'Afroasiatic',
            'population_2021' => '0.11%',
            'internet_content' => '0.40%',
            'wikipedia_content' => '0.59%',
            'script' => 'Hebrew',
            'writing_family' => 'Hebrew Script',
            'writing_system' => 'Abjad',
            'countries' => 1,
        ],
        [
            'language_id' => 132,
            'rank' => 20,
            'language' => 'Serbian',
            'family_spoken' => 'Indoeuropean',
            'population_2021' => '0.11%',
            'internet_content' => '0.20%',
            'wikipedia_content' => '1.08%',
            'script' => 'Cyrillic',
            'writing_family' => 'Cyrillic Script',
            'writing_system' => 'Alphabetical',
            'countries' => 2,
        ],
        [
            'language_id' => 20,
            'rank' => 21,
            'language' => 'Bulgarian',
            'family_spoken' => 'Indoeuropean',
            'population_2021' => '0.10%',
            'internet_content' => '0.30%',
            'wikipedia_content' => '0.46%',
            'script' => 'Cyrillic',
            'writing_family' => 'Cyrillic Script',
            'writing_system' => 'Alphabetical',
            'countries' => 1,
        ],
        [
            'language_id' => 45,
            'rank' => 22,
            'language' => 'Finnish',
            'family_spoken' => 'Indoeuropean',
            'population_2021' => '0.09%',
            'internet_content' => '0.40%',
            'wikipedia_content' => '0.92%',
            'script' => 'Latin',
            'writing_family' => 'Latin Script',
            'writing_system' => 'Alphabetical',
            'countries' => 1,
        ],
        [
            'language_id' => 34,
            'rank' => 23,
            'language' => 'Danish',
            'family_spoken' => 'Indoeuropean',
            'population_2021' => '0.09%',
            'internet_content' => '0.40%',
            'wikipedia_content' => '0.47%',
            'script' => 'Latin',
            'writing_family' => 'Latin Script',
            'writing_system' => 'Alphabetical',
            'countries' => 1,
        ],
        [
            'language_id' => 113,
            'rank' => 24,
            'language' => 'Norwegian',
            'family_spoken' => 'Indoeuropean',
            'population_2021' => '0.09%',
            'internet_content' => '0.10%',
            'wikipedia_content' => '1.01%',
            'script' => 'Latin',
            'writing_family' => 'Latin Script',
            'writing_system' => 'Alphabetical',
            'countries' => 1,
        ],
        [
            'language_id' => 32,
            'rank' => 25,
            'language' => 'Croatian',
            'family_spoken' => 'Indoeuropean',
            'population_2021' => '0.07%',
            'internet_content' => '0.20%',
            'wikipedia_content' => '0.34%',
            'script' => 'Latin',
            'writing_family' => 'Latin Script',
            'writing_system' => 'Alphabetical',
            'countries' => 2,
        ],
        [
            'language_id' => 138,
            'rank' => 26,
            'language' => 'Slovak',
            'family_spoken' => 'Indoeuropean',
            'population_2021' => '0.07%',
            'internet_content' => '0.40%',
            'wikipedia_content' => '0.39%',
            'script' => 'Latin',
            'writing_family' => 'Latin Script',
            'writing_system' => 'Alphabetical',
            'countries' => 2,
        ],
        [
            'language_id' => 84,
            'rank' => 27,
            'language' => 'Lithuanian',
            'family_spoken' => 'Indoeuropean',
            'population_2021' => '0.04%',
            'internet_content' => '0.20%',
            'wikipedia_content' => '0.34%',
            'script' => 'Latin',
            'writing_family' => 'Latin Script',
            'writing_system' => 'Alphabetical',
            'countries' => 1,
        ],
        [
            'language_id' => 139,
            'rank' => 28,
            'language' => 'Slovene',
            'family_spoken' => 'Indoeuropean',
            'population_2021' => '0.03%',
            'internet_content' => '0.10%',
            'wikipedia_content' => '0.30%',
            'script' => 'Latin',
            'writing_family' => 'Latin Script',
            'writing_system' => 'Alphabetical',
            'countries' => 1,
        ],
        [
            'language_id' => 82,
            'rank' => 29,
            'language' => 'Latvian',
            'family_spoken' => 'Indoeuropean',
            'population_2021' => '0.02%',
            'internet_content' => '0.10%',
            'wikipedia_content' => '0.21%',
            'script' => 'Latin',
            'writing_family' => 'Latin Script',
            'writing_system' => 'Alphabetical',
            'countries' => 1,
        ],
        [
            'language_id' => 41,
            'rank' => 30,
            'language' => 'Estonian',
            'family_spoken' => 'Others',
            'population_2021' => '0.02%',
            'internet_content' => '0.10%',
            'wikipedia_content' => '0.39%',
            'script' => 'Latin',
            'writing_family' => 'Latin Script',
            'writing_system' => 'Alphabetical',
            'countries' => 1,
        ],

    ],









];
