<?php

return [
    'villages' => [
        [
            "id" => "1",
            "state_ut" => "Andhra Pradesh",
            "Assamese" => "0.00",
            "Bengali" => "0.04",
            "Hindi" => "4.00",
            "Punjabi" => "0.00",
            "Kannada" => "0.71",
            "Malayalam" => "0.01",
            "Marathi" => "0.77",
            "Gujarati" => "0.01",
            "Odia" => "0.47",
            "Urdu" => "4.45",
            "Tamil" => "0.69",
            "Telugu" => "87.56",
            "English" => "0.00",
            "Other_MT" => "1.28",
            "No_of_Gram_Panchayats" => "13326",
            "No_of_Cities" => "20863"
        ],
        [
            "id" => "2",
            "state_ut" => "Arunachal Pradesh",
            "Assamese" => "3.30",
            "Bengali" => "6.25",
            "Hindi" => "4.75",
            "Punjabi" => "0.16",
            "Kannada" => "0.03",
            "Malayalam" => "0.15",
            "Marathi" => "0.14",
            "Gujarati" => "0.02",
            "Odia" => "0.44",
            "Urdu" => "0.06",
            "Tamil" => "0.08",
            "Telugu" => "0.09",
            "English" => "0.01",
            "Other_MT" => "84.52",
            "No_of_Gram_Panchayats" => "2108",
            "No_of_Cities" => "5849"
        ],
        [
            "id" => "3",
            "state_ut" => "Assam",
            "Assamese" => "48.64",
            "Bengali" => "28.21",
            "Hindi" => "5.80",
            "Punjabi" => "0.04",
            "Kannada" => "0.01",
            "Malayalam" => "0.01",
            "Marathi" => "0.04",
            "Gujarati" => "0.02",
            "Odia" => "0.78",
            "Urdu" => "0.02",
            "Tamil" => "0.01",
            "Telugu" => "0.04",
            "English" => "0.00",
            "Other_MT" => "16.36",
            "No_of_Gram_Panchayats" => "2192",
            "No_of_Cities" => "28956"
        ],
        [
            "id" => "4",
            "state_ut" => "Bihar",
            "Assamese" => "0.00",
            "Bengali" => "0.79",
            "Hindi" => "77.30",
            "Punjabi" => "0.00",
            "Kannada" => "0.00",
            "Malayalam" => "0.00",
            "Marathi" => "0.00",
            "Gujarati" => "0.01",
            "Odia" => "0.00",
            "Urdu" => "7.71",
            "Tamil" => "0.00",
            "Telugu" => "0.00",
            "English" => "0.00",
            "Other_MT" => "14.17",
            "No_of_Gram_Panchayats" => "8052",
            "No_of_Cities" => "49392"
        ],
        [
            "id" => "5",
            "state_ut" => "Chhattisgarh",
            "Assamese" => "0.01",
            "Bengali" => "0.67",
            "Hindi" => "83.51",
            "Punjabi" => "0.02",
            "Kannada" => "0.00",
            "Malayalam" => "0.01",
            "Marathi" => "0.20",
            "Gujarati" => "0.03",
            "Odia" => "3.73",
            "Urdu" => "0.05",
            "Tamil" => "0.01",
            "Telugu" => "0.26",
            "English" => "0.00",
            "Other_MT" => "11.52",
            "No_of_Gram_Panchayats" => "11691",
            "No_of_Cities" => "20666"
        ],
        [
            "id" => "6",
            "state_ut" => "Goa",
            "Assamese" => "0.06",
            "Bengali" => "0.23",
            "Hindi" => "4.88",
            "Punjabi" => "0.06",
            "Kannada" => "2.53",
            "Malayalam" => "0.32",
            "Marathi" => "13.00",
            "Gujarati" => "0.16",
            "Odia" => "0.24",
            "Urdu" => "0.94",
            "Tamil" => "0.23",
            "Telugu" => "0.42",
            "English" => "0.38",
            "Other_MT" => "76.55",
            "No_of_Gram_Panchayats" => "191",
            "No_of_Cities" => "435"
        ],
        [
            "id" => "7",
            "state_ut" => "Gujarat",
            "Assamese" => "0.00",
            "Bengali" => "0.03",
            "Hindi" => "1.47",
            "Punjabi" => "0.02",
            "Kannada" => "0.01",
            "Malayalam" => "0.01",
            "Marathi" => "0.18",
            "Gujarati" => "93.56",
            "Odia" => "0.04",
            "Urdu" => "0.05",
            "Tamil" => "0.01",
            "Telugu" => "0.01",
            "English" => "0.00",
            "Other_MT" => "4.61",
            "No_of_Gram_Panchayats" => "14621",
            "No_of_Cities" => "19886"
        ],
        [
            "id" => "8",
            "state_ut" => "Haryana",
            "Assamese" => "0.01",
            "Bengali" => "0.09",
            "Hindi" => "87.51",
            "Punjabi" => "10.09",
            "Kannada" => "0.00",
            "Malayalam" => "0.01",
            "Marathi" => "0.01",
            "Gujarati" => "0.01",
            "Odia" => "0.02",
            "Urdu" => "1.99",
            "Tamil" => "0.01",
            "Telugu" => "0.01",
            "English" => "0.00",
            "Other_MT" => "0.25",
            "No_of_Gram_Panchayats" => "6230",
            "No_of_Cities" => "7593"
        ],
        [
            "id" => "9",
            "state_ut" => "Himachal Pradesh",
            "Assamese" => "0.01",
            "Bengali" => "0.07",
            "Hindi" => "86.24",
            "Punjabi" => "8.83",
            "Kannada" => "0.00",
            "Malayalam" => "0.01",
            "Marathi" => "0.04",
            "Gujarati" => "0.15",
            "Odia" => "0.03",
            "Urdu" => "0.06",
            "Tamil" => "0.01",
            "Telugu" => "0.01",
            "English" => "0.01",
            "Other_MT" => "4.53",
            "No_of_Gram_Panchayats" => "3615",
            "No_of_Cities" => "21763"
        ],
        [
            "id" => "10",
            "state_ut" => "Jharkhand",
            "Assamese" => "0.00",
            "Bengali" => "9.69",
            "Hindi" => "60.13",
            "Punjabi" => "0.01",
            "Kannada" => "0.00",
            "Malayalam" => "0.00",
            "Marathi" => "0.02",
            "Gujarati" => "0.03",
            "Odia" => "1.49",
            "Urdu" => "4.24",
            "Tamil" => "0.00",
            "Telugu" => "0.01",
            "English" => "0.00",
            "Other_MT" => "24.37",
            "No_of_Gram_Panchayats" => "4346",
            "No_of_Cities" => "32944"
        ],
        [
            "id" => "11",
            "state_ut" => "Karnataka",
            "Assamese" => "0.01",
            "Bengali" => "0.06",
            "Hindi" => "2.90",
            "Punjabi" => "0.00",
            "Kannada" => "77.51",
            "Malayalam" => "0.91",
            "Marathi" => "3.30",
            "Gujarati" => "0.03",
            "Odia" => "0.04",
            "Urdu" => "5.72",
            "Tamil" => "0.89",
            "Telugu" => "4.32",
            "English" => "0.00",
            "Other_MT" => "4.31",
            "No_of_Gram_Panchayats" => "5949",
            "No_of_Cities" => "30774"
        ],
        [
            "id" => "12",
            "state_ut" => "Kerala",
            "Assamese" => "0.02",
            "Bengali" => "0.07",
            "Hindi" => "0.07",
            "Punjabi" => "0.00",
            "Kannada" => "0.33",
            "Malayalam" => "96.54",
            "Marathi" => "0.14",
            "Gujarati" => "0.00",
            "Odia" => "0.02",
            "Urdu" => "0.02",
            "Tamil" => "1.98",
            "Telugu" => "0.10",
            "English" => "0.01",
            "Other_MT" => "0.69",
            "No_of_Gram_Panchayats" => "941",
            "No_of_Cities" => "1829"
        ],
        [
            "id" => "13",
            "state_ut" => "Madhya Pradesh",
            "Assamese" => "0.00",
            "Bengali" => "0.09",
            "Hindi" => "87.99",
            "Punjabi" => "0.08",
            "Kannada" => "0.00",
            "Malayalam" => "0.01",
            "Marathi" => "1.44",
            "Gujarati" => "0.15",
            "Odia" => "0.01",
            "Urdu" => "0.29",
            "Tamil" => "0.00",
            "Telugu" => "0.01",
            "English" => "0.00",
            "Other_MT" => "9.94",
            "No_of_Gram_Panchayats" => "23011",
            "No_of_Cities" => "57503"
        ],
        [
            "id" => "14",
            "state_ut" => "Maharashtra",
            "Assamese" => "0.00",
            "Bengali" => "0.14",
            "Hindi" => "6.60",
            "Punjabi" => "0.02",
            "Kannada" => "0.83",
            "Malayalam" => "0.02",
            "Marathi" => "81.18",
            "Gujarati" => "0.21",
            "Odia" => "0.02",
            "Urdu" => "2.67",
            "Tamil" => "0.03",
            "Telugu" => "0.67",
            "English" => "0.00",
            "Other_MT" => "7.59",
            "No_of_Gram_Panchayats" => "28002",
            "No_of_Cities" => "45031"
        ],
        [
            "id" => "15",
            "state_ut" => "Manipur",
            "Assamese" => "0.08",
            "Bengali" => "1.24",
            "Hindi" => "0.75",
            "Punjabi" => "0.03",
            "Kannada" => "0.02",
            "Malayalam" => "0.04",
            "Marathi" => "0.07",
            "Gujarati" => "0.00",
            "Odia" => "0.03",
            "Urdu" => "0.01",
            "Tamil" => "0.03",
            "Telugu" => "0.03",
            "English" => "0.01",
            "Other_MT" => "97.64",
            "No_of_Gram_Panchayats" => "162",
            "No_of_Cities" => "3853"
        ],
        [
            "id" => "16",
            "state_ut" => "Meghalaya",
            "Assamese" => "1.19",
            "Bengali" => "7.24",
            "Hindi" => "0.78",
            "Punjabi" => "0.03",
            "Kannada" => "0.00",
            "Malayalam" => "0.03",
            "Marathi" => "0.70",
            "Gujarati" => "0.01",
            "Odia" => "0.03",
            "Urdu" => "0.01",
            "Tamil" => "0.01",
            "Telugu" => "0.02",
            "English" => "0.00",
            "Other_MT" => "89.95",
            "No_of_Gram_Panchayats" => "0",
            "No_of_Cities" => "7201"
        ],
        [
            "id" => "17",
            "state_ut" => "Mizoram",
            "Assamese" => "0.05",
            "Bengali" => "18.42",
            "Hindi" => "0.39",
            "Punjabi" => "0.02",
            "Kannada" => "0.01",
            "Malayalam" => "0.02",
            "Marathi" => "0.04",
            "Gujarati" => "0.00",
            "Odia" => "0.01",
            "Urdu" => "0.01",
            "Tamil" => "0.02",
            "Telugu" => "0.02",
            "English" => "0.00",
            "Other_MT" => "81.00",
            "No_of_Gram_Panchayats" => "0",
            "No_of_Cities" => "887"
        ],
        [
            "id" => "18",
            "state_ut" => "Nagaland",
            "Assamese" => "0.63",
            "Bengali" => "1.69",
            "Hindi" => "1.23",
            "Punjabi" => "0.09",
            "Kannada" => "0.01",
            "Malayalam" => "0.07",
            "Marathi" => "0.08",
            "Gujarati" => "0.01",
            "Odia" => "0.16",
            "Urdu" => "0.02",
            "Tamil" => "0.03",
            "Telugu" => "0.03",
            "English" => "0.01",
            "Other_MT" => "95.96",
            "No_of_Gram_Panchayats" => "0",
            "No_of_Cities" => "1550"
        ],
        [
            "id" => "19",
            "state_ut" => "Odisha",
            "Assamese" => "0.00",
            "Bengali" => "1.03",
            "Hindi" => "1.98",
            "Punjabi" => "0.01",
            "Kannada" => "0.01",
            "Malayalam" => "0.01",
            "Marathi" => "0.01",
            "Gujarati" => "0.01",
            "Odia" => "83.72",
            "Urdu" => "1.07",
            "Tamil" => "0.01",
            "Telugu" => "1.02",
            "English" => "0.00",
            "Other_MT" => "11.12",
            "No_of_Gram_Panchayats" => "6783",
            "No_of_Cities" => "51800"
        ],
        [
            "id" => "20",
            "state_ut" => "Punjab",
            "Assamese" => "0.00",
            "Bengali" => "0.03",
            "Hindi" => "4.38",
            "Punjabi" => "95.33",
            "Kannada" => "0.00",
            "Malayalam" => "0.01",
            "Marathi" => "0.01",
            "Gujarati" => "0.02",
            "Odia" => "0.01",
            "Urdu" => "0.06",
            "Tamil" => "0.01",
            "Telugu" => "0.01",
            "English" => "0.00",
            "Other_MT" => "0.13",
            "No_of_Gram_Panchayats" => "13236",
            "No_of_Cities" => "15093"
        ],
        [
            "id" => "21",
            "state_ut" => "Rajasthan",
            "Assamese" => "0.00",
            "Bengali" => "0.06",
            "Hindi" => "88.82",
            "Punjabi" => "3.61",
            "Kannada" => "0.00",
            "Malayalam" => "0.01",
            "Marathi" => "0.01",
            "Gujarati" => "0.06",
            "Odia" => "0.01",
            "Urdu" => "0.22",
            "Tamil" => "0.00",
            "Telugu" => "0.00",
            "English" => "0.02",
            "Other_MT" => "7.16",
            "No_of_Gram_Panchayats" => "11070",
            "No_of_Cities" => "52262"
        ],
        [
            "id" => "22",
            "state_ut" => "Sikkim",
            "Assamese" => "0.12",
            "Bengali" => "0.65",
            "Hindi" => "3.93",
            "Punjabi" => "0.37",
            "Kannada" => "0.06",
            "Malayalam" => "0.12",
            "Marathi" => "0.13",
            "Gujarati" => "0.02",
            "Odia" => "0.10",
            "Urdu" => "0.13",
            "Tamil" => "0.12",
            "Telugu" => "0.16",
            "English" => "0.01",
            "Other_MT" => "94.09",
            "No_of_Gram_Panchayats" => "199",
            "No_of_Cities" => "495"
        ],
        [
            "id" => "23",
            "state_ut" => "Tamil Nadu",
            "Assamese" => "0.00",
            "Bengali" => "0.01",
            "Hindi" => "0.13",
            "Punjabi" => "0.00",
            "Kannada" => "1.87",
            "Malayalam" => "0.29",
            "Marathi" => "0.05",
            "Gujarati" => "0.05",
            "Odia" => "0.02",
            "Urdu" => "0.65",
            "Tamil" => "91.59",
            "Telugu" => "5.30",
            "English" => "0.01",
            "Other_MT" => "0.03",
            "No_of_Gram_Panchayats" => "12480",
            "No_of_Cities" => "20147"
        ],
        [
            "id" => "24",
            "state_ut" => "Telangana",
            "Assamese" => "0.00",
            "Bengali" => "0.04",
            "Hindi" => "4.00",
            "Punjabi" => "0.00",
            "Kannada" => "0.71",
            "Malayalam" => "0.01",
            "Marathi" => "0.77",
            "Gujarati" => "0.01",
            "Odia" => "0.47",
            "Urdu" => "4.45",
            "Tamil" => "0.69",
            "Telugu" => "87.56",
            "English" => "0.00",
            "Other_MT" => "1.28",
            "No_of_Gram_Panchayats" => "12760",
            "No_of_Cities" => "16700"
        ],
        [
            "id" => "25",
            "state_ut" => "Tripura",
            "Assamese" => "0.04",
            "Bengali" => "56.48",
            "Hindi" => "2.08",
            "Punjabi" => "0.02",
            "Kannada" => "0.02",
            "Malayalam" => "0.02",
            "Marathi" => "0.03",
            "Gujarati" => "0.04",
            "Odia" => "0.88",
            "Urdu" => "0.02",
            "Tamil" => "0.02",
            "Telugu" => "0.13",
            "English" => "0.00",
            "Other_MT" => "40.21",
            "No_of_Gram_Panchayats" => "607",
            "No_of_Cities" => "1248"
        ],
        [
            "id" => "26",
            "state_ut" => "Uttar Pradesh",
            "Assamese" => "0.00",
            "Bengali" => "0.08",
            "Hindi" => "96.54",
            "Punjabi" => "0.21",
            "Kannada" => "0.00",
            "Malayalam" => "0.00",
            "Marathi" => "0.00",
            "Gujarati" => "0.00",
            "Odia" => "0.00",
            "Urdu" => "3.12",
            "Tamil" => "0.00",
            "Telugu" => "0.00",
            "English" => "0.00",
            "Other_MT" => "0.02",
            "No_of_Gram_Panchayats" => "57695",
            "No_of_Cities" => "110274"
        ],
        [
            "id" => "27",
            "state_ut" => "Uttarakhand",
            "Assamese" => "0.01",
            "Bengali" => "1.45",
            "Hindi" => "90.76",
            "Punjabi" => "2.58",
            "Kannada" => "0.00",
            "Malayalam" => "0.01",
            "Marathi" => "0.03",
            "Gujarati" => "0.03",
            "Odia" => "0.02",
            "Urdu" => "2.66",
            "Tamil" => "0.01",
            "Telugu" => "0.01",
            "English" => "0.01",
            "Other_MT" => "2.43",
            "No_of_Gram_Panchayats" => "7817",
            "No_of_Cities" => "17346"
        ],
        [
            "id" => "28",
            "state_ut" => "West Bengal",
            "Assamese" => "0.01",
            "Bengali" => "90.36",
            "Hindi" => "3.26",
            "Punjabi" => "0.01",
            "Kannada" => "0.00",
            "Malayalam" => "0.00",
            "Marathi" => "0.01",
            "Gujarati" => "0.01",
            "Odia" => "0.06",
            "Urdu" => "0.53",
            "Tamil" => "0.00",
            "Telugu" => "0.01",
            "English" => "0.00",
            "Other_MT" => "5.74",
            "No_of_Gram_Panchayats" => "3339",
            "No_of_Cities" => "41416"
        ],
        [
            "id" => "29",
            "state_ut" => "Andaman and Nicobar",
            "Assamese" => "0.01",
            "Bengali" => "37.89",
            "Hindi" => "17.75",
            "Punjabi" => "0.31",
            "Kannada" => "0.03",
            "Malayalam" => "6.09",
            "Marathi" => "0.13",
            "Gujarati" => "0.03",
            "Odia" => "0.20",
            "Urdu" => "0.08",
            "Tamil" => "9.55",
            "Telugu" => "7.35",
            "English" => "0.02",
            "Other_MT" => "20.57",
            "No_of_Gram_Panchayats" => "71",
            "No_of_Cities" => "561"
        ],
        [
            "id" => "30",
            "state_ut" => "Chandigarh",
            "Assamese" => "0.10",
            "Bengali" => "0.61",
            "Hindi" => "70.30",
            "Punjabi" => "25.29",
            "Kannada" => "0.00",
            "Malayalam" => "0.07",
            "Marathi" => "0.05",
            "Gujarati" => "0.03",
            "Odia" => "0.11",
            "Urdu" => "0.84",
            "Tamil" => "0.02",
            "Telugu" => "0.08",
            "English" => "0.00",
            "Other_MT" => "2.50",
            "No_of_Gram_Panchayats" => "0",
            "No_of_Cities" => "0"
        ],
        [
            "id" => "31",
            "state_ut" => "Dadra and Nagar Haveli and Daman and Diu",
            "Assamese" => "0.23",
            "Bengali" => "0.40",
            "Hindi" => "10.55",
            "Punjabi" => "0.03",
            "Kannada" => "0.05",
            "Malayalam" => "0.10",
            "Marathi" => "2.46",
            "Gujarati" => "33.18",
            "Odia" => "0.66",
            "Urdu" => "0.14",
            "Tamil" => "0.04",
            "Telugu" => "0.04",
            "English" => "0.02",
            "Other_MT" => "52.11",
            "No_of_Gram_Panchayats" => "50",
            "No_of_Cities" => "118"
        ],
        [
            "id" => "32",
            "state_ut" => "Jammu and Kashmir",
            "Assamese" => "0.03",
            "Bengali" => "0.08",
            "Hindi" => "24.82",
            "Punjabi" => "1.02",
            "Kannada" => "0.03",
            "Malayalam" => "0.04",
            "Marathi" => "0.09",
            "Gujarati" => "0.10",
            "Odia" => "0.03",
            "Urdu" => "0.09",
            "Tamil" => "0.05",
            "Telugu" => "0.05",
            "English" => "0.01",
            "Other_MT" => "73.57",
            "No_of_Gram_Panchayats" => "4291",
            "No_of_Cities" => "7914"
        ],
        [
            "id" => "33",
            "state_ut" => "Ladakh",
            "Assamese" => "0.03",
            "Bengali" => "0.08",
            "Hindi" => "24.82",
            "Punjabi" => "1.02",
            "Kannada" => "0.03",
            "Malayalam" => "0.04",
            "Marathi" => "0.09",
            "Gujarati" => "0.10",
            "Odia" => "0.03",
            "Urdu" => "0.09",
            "Tamil" => "0.05",
            "Telugu" => "0.05",
            "English" => "0.01",
            "Other_MT" => "73.57",
            "No_of_Gram_Panchayats" => "193",
            "No_of_Cities" => "272"
        ],
        [
            "id" => "34",
            "state_ut" => "Lakshadweep",
            "Assamese" => "0.00",
            "Bengali" => "0.06",
            "Hindi" => "0.12",
            "Punjabi" => "0.00",
            "Kannada" => "0.15",
            "Malayalam" => "98.08",
            "Marathi" => "0.04",
            "Gujarati" => "0.02",
            "Odia" => "0.09",
            "Urdu" => "0.00",
            "Tamil" => "1.03",
            "Telugu" => "0.03",
            "English" => "0.00",
            "Other_MT" => "0.38",
            "No_of_Gram_Panchayats" => "10",
            "No_of_Cities" => "27"
        ],
        [
            "id" => "35",
            "state_ut" => "National Capital Territory of Delhi",
            "Assamese" => "0.01",
            "Bengali" => "0.92",
            "Hindi" => "95.89",
            "Punjabi" => "1.15",
            "Kannada" => "0.00",
            "Malayalam" => "0.04",
            "Marathi" => "0.09",
            "Gujarati" => "0.02",
            "Odia" => "0.08",
            "Urdu" => "0.70",
            "Tamil" => "0.03",
            "Telugu" => "0.03",
            "English" => "0.01",
            "Other_MT" => "1.04",
            "No_of_Gram_Panchayats" => "0",
            "No_of_Cities" => "222"
        ],
        [
            "id" => "36",
            "state_ut" => "Puducherry",
            "Assamese" => "0.00",
            "Bengali" => "0.02",
            "Hindi" => "0.23",
            "Punjabi" => "0.00",
            "Kannada" => "0.04",
            "Malayalam" => "0.09",
            "Marathi" => "0.01",
            "Gujarati" => "0.01",
            "Odia" => "0.12",
            "Urdu" => "0.15",
            "Tamil" => "98.64",
            "Telugu" => "0.64",
            "English" => "0.00",
            "Other_MT" => "0.04",
            "No_of_Gram_Panchayats" => "108",
            "No_of_Cities" => "172"
        ],

    ]

];
